// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeagentInfo")
public inline fun agentInfo(block: mrt.AgentInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.AgentInfo =
  mrt.AgentInfoKt.Dsl._create(mrt.Mrt.AgentInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.AgentInfo`
 */
public object AgentInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.AgentInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.AgentInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.AgentInfo = _builder.build()

    /**
     * `string agent_version = 1;`
     */
    public var agentVersion: kotlin.String
      @kotlin.jvm.JvmName("getAgentVersion")
        get() = _builder.agentVersion
      @kotlin.jvm.JvmName("setAgentVersion")
        set(value) {
        _builder.agentVersion = value
      }
    /**
     * `string agent_version = 1;`
     */
    public fun clearAgentVersion() {
      _builder.clearAgentVersion()
    }

    /**
     * ```
     * "codex-app-server", "codex-cli", "mock"
     * ```
     *
     * `string adapter_type = 2;`
     */
    public var adapterType: kotlin.String
      @kotlin.jvm.JvmName("getAdapterType")
        get() = _builder.adapterType
      @kotlin.jvm.JvmName("setAdapterType")
        set(value) {
        _builder.adapterType = value
      }
    /**
     * ```
     * "codex-app-server", "codex-cli", "mock"
     * ```
     *
     * `string adapter_type = 2;`
     */
    public fun clearAdapterType() {
      _builder.clearAdapterType()
    }

    /**
     * `string hostname = 3;`
     */
    public var hostname: kotlin.String
      @kotlin.jvm.JvmName("getHostname")
        get() = _builder.hostname
      @kotlin.jvm.JvmName("setHostname")
        set(value) {
        _builder.hostname = value
      }
    /**
     * `string hostname = 3;`
     */
    public fun clearHostname() {
      _builder.clearHostname()
    }

    /**
     * `string os = 4;`
     */
    public var os: kotlin.String
      @kotlin.jvm.JvmName("getOs")
        get() = _builder.os
      @kotlin.jvm.JvmName("setOs")
        set(value) {
        _builder.os = value
      }
    /**
     * `string os = 4;`
     */
    public fun clearOs() {
      _builder.clearOs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.AgentInfo.copy(block: `mrt`.AgentInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.AgentInfo =
  `mrt`.AgentInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

