// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeagentEvent")
public inline fun agentEvent(block: mrt.AgentEventKt.Dsl.() -> kotlin.Unit): mrt.Mrt.AgentEvent =
  mrt.AgentEventKt.Dsl._create(mrt.Mrt.AgentEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.AgentEvent`
 */
public object AgentEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.AgentEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.AgentEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.AgentEvent = _builder.build()

    /**
     * `.mrt.CodexOutput codex_output = 1;`
     */
    public var codexOutput: mrt.Mrt.CodexOutput
      @kotlin.jvm.JvmName("getCodexOutput")
        get() = _builder.codexOutput
      @kotlin.jvm.JvmName("setCodexOutput")
        set(value) {
        _builder.codexOutput = value
      }
    /**
     * `.mrt.CodexOutput codex_output = 1;`
     */
    public fun clearCodexOutput() {
      _builder.clearCodexOutput()
    }
    /**
     * `.mrt.CodexOutput codex_output = 1;`
     * @return Whether the codexOutput field is set.
     */
    public fun hasCodexOutput(): kotlin.Boolean {
      return _builder.hasCodexOutput()
    }

    /**
     * `.mrt.ApprovalRequest approval_request = 2;`
     */
    public var approvalRequest: mrt.Mrt.ApprovalRequest
      @kotlin.jvm.JvmName("getApprovalRequest")
        get() = _builder.approvalRequest
      @kotlin.jvm.JvmName("setApprovalRequest")
        set(value) {
        _builder.approvalRequest = value
      }
    /**
     * `.mrt.ApprovalRequest approval_request = 2;`
     */
    public fun clearApprovalRequest() {
      _builder.clearApprovalRequest()
    }
    /**
     * `.mrt.ApprovalRequest approval_request = 2;`
     * @return Whether the approvalRequest field is set.
     */
    public fun hasApprovalRequest(): kotlin.Boolean {
      return _builder.hasApprovalRequest()
    }

    /**
     * `.mrt.TaskStatusUpdate status_update = 3;`
     */
    public var statusUpdate: mrt.Mrt.TaskStatusUpdate
      @kotlin.jvm.JvmName("getStatusUpdate")
        get() = _builder.statusUpdate
      @kotlin.jvm.JvmName("setStatusUpdate")
        set(value) {
        _builder.statusUpdate = value
      }
    /**
     * `.mrt.TaskStatusUpdate status_update = 3;`
     */
    public fun clearStatusUpdate() {
      _builder.clearStatusUpdate()
    }
    /**
     * `.mrt.TaskStatusUpdate status_update = 3;`
     * @return Whether the statusUpdate field is set.
     */
    public fun hasStatusUpdate(): kotlin.Boolean {
      return _builder.hasStatusUpdate()
    }

    /**
     * `.mrt.SessionListUpdate session_list = 4;`
     */
    public var sessionList: mrt.Mrt.SessionListUpdate
      @kotlin.jvm.JvmName("getSessionList")
        get() = _builder.sessionList
      @kotlin.jvm.JvmName("setSessionList")
        set(value) {
        _builder.sessionList = value
      }
    /**
     * `.mrt.SessionListUpdate session_list = 4;`
     */
    public fun clearSessionList() {
      _builder.clearSessionList()
    }
    /**
     * `.mrt.SessionListUpdate session_list = 4;`
     * @return Whether the sessionList field is set.
     */
    public fun hasSessionList(): kotlin.Boolean {
      return _builder.hasSessionList()
    }

    /**
     * `.mrt.AgentInfo agent_info = 5;`
     */
    public var agentInfo: mrt.Mrt.AgentInfo
      @kotlin.jvm.JvmName("getAgentInfo")
        get() = _builder.agentInfo
      @kotlin.jvm.JvmName("setAgentInfo")
        set(value) {
        _builder.agentInfo = value
      }
    /**
     * `.mrt.AgentInfo agent_info = 5;`
     */
    public fun clearAgentInfo() {
      _builder.clearAgentInfo()
    }
    /**
     * `.mrt.AgentInfo agent_info = 5;`
     * @return Whether the agentInfo field is set.
     */
    public fun hasAgentInfo(): kotlin.Boolean {
      return _builder.hasAgentInfo()
    }

    /**
     * `.mrt.ErrorEvent error = 10;`
     */
    public var error: mrt.Mrt.ErrorEvent
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.mrt.ErrorEvent error = 10;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.mrt.ErrorEvent error = 10;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }
    public val evtCase: mrt.Mrt.AgentEvent.EvtCase
    @kotlin.jvm.JvmName("getEvtCase")
      get() = _builder.getEvtCase()

    public fun clearEvt() {
      _builder.clearEvt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.AgentEvent.copy(block: `mrt`.AgentEventKt.Dsl.() -> kotlin.Unit): mrt.Mrt.AgentEvent =
  `mrt`.AgentEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.AgentEventOrBuilder.codexOutputOrNull: mrt.Mrt.CodexOutput?
  get() = if (hasCodexOutput()) getCodexOutput() else null

public val mrt.Mrt.AgentEventOrBuilder.approvalRequestOrNull: mrt.Mrt.ApprovalRequest?
  get() = if (hasApprovalRequest()) getApprovalRequest() else null

public val mrt.Mrt.AgentEventOrBuilder.statusUpdateOrNull: mrt.Mrt.TaskStatusUpdate?
  get() = if (hasStatusUpdate()) getStatusUpdate() else null

public val mrt.Mrt.AgentEventOrBuilder.sessionListOrNull: mrt.Mrt.SessionListUpdate?
  get() = if (hasSessionList()) getSessionList() else null

public val mrt.Mrt.AgentEventOrBuilder.agentInfoOrNull: mrt.Mrt.AgentInfo?
  get() = if (hasAgentInfo()) getAgentInfo() else null

public val mrt.Mrt.AgentEventOrBuilder.errorOrNull: mrt.Mrt.ErrorEvent?
  get() = if (hasError()) getError() else null

