// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeagentCommand")
public inline fun agentCommand(block: mrt.AgentCommandKt.Dsl.() -> kotlin.Unit): mrt.Mrt.AgentCommand =
  mrt.AgentCommandKt.Dsl._create(mrt.Mrt.AgentCommand.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.AgentCommand`
 */
public object AgentCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.AgentCommand.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.AgentCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.AgentCommand = _builder.build()

    /**
     * `.mrt.SendPrompt send_prompt = 1;`
     */
    public var sendPrompt: mrt.Mrt.SendPrompt
      @kotlin.jvm.JvmName("getSendPrompt")
        get() = _builder.sendPrompt
      @kotlin.jvm.JvmName("setSendPrompt")
        set(value) {
        _builder.sendPrompt = value
      }
    /**
     * `.mrt.SendPrompt send_prompt = 1;`
     */
    public fun clearSendPrompt() {
      _builder.clearSendPrompt()
    }
    /**
     * `.mrt.SendPrompt send_prompt = 1;`
     * @return Whether the sendPrompt field is set.
     */
    public fun hasSendPrompt(): kotlin.Boolean {
      return _builder.hasSendPrompt()
    }

    /**
     * `.mrt.ApprovalResponse approval_response = 2;`
     */
    public var approvalResponse: mrt.Mrt.ApprovalResponse
      @kotlin.jvm.JvmName("getApprovalResponse")
        get() = _builder.approvalResponse
      @kotlin.jvm.JvmName("setApprovalResponse")
        set(value) {
        _builder.approvalResponse = value
      }
    /**
     * `.mrt.ApprovalResponse approval_response = 2;`
     */
    public fun clearApprovalResponse() {
      _builder.clearApprovalResponse()
    }
    /**
     * `.mrt.ApprovalResponse approval_response = 2;`
     * @return Whether the approvalResponse field is set.
     */
    public fun hasApprovalResponse(): kotlin.Boolean {
      return _builder.hasApprovalResponse()
    }

    /**
     * `.mrt.CancelTask cancel_task = 3;`
     */
    public var cancelTask: mrt.Mrt.CancelTask
      @kotlin.jvm.JvmName("getCancelTask")
        get() = _builder.cancelTask
      @kotlin.jvm.JvmName("setCancelTask")
        set(value) {
        _builder.cancelTask = value
      }
    /**
     * `.mrt.CancelTask cancel_task = 3;`
     */
    public fun clearCancelTask() {
      _builder.clearCancelTask()
    }
    /**
     * `.mrt.CancelTask cancel_task = 3;`
     * @return Whether the cancelTask field is set.
     */
    public fun hasCancelTask(): kotlin.Boolean {
      return _builder.hasCancelTask()
    }

    /**
     * `.mrt.GetStatus get_status = 4;`
     */
    public var getStatus: mrt.Mrt.GetStatus
      @kotlin.jvm.JvmName("getGetStatus")
        get() = _builder.getStatus
      @kotlin.jvm.JvmName("setGetStatus")
        set(value) {
        _builder.getStatus = value
      }
    /**
     * `.mrt.GetStatus get_status = 4;`
     */
    public fun clearGetStatus() {
      _builder.clearGetStatus()
    }
    /**
     * `.mrt.GetStatus get_status = 4;`
     * @return Whether the getStatus field is set.
     */
    public fun hasGetStatus(): kotlin.Boolean {
      return _builder.hasGetStatus()
    }
    public val cmdCase: mrt.Mrt.AgentCommand.CmdCase
    @kotlin.jvm.JvmName("getCmdCase")
      get() = _builder.getCmdCase()

    public fun clearCmd() {
      _builder.clearCmd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.AgentCommand.copy(block: `mrt`.AgentCommandKt.Dsl.() -> kotlin.Unit): mrt.Mrt.AgentCommand =
  `mrt`.AgentCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.AgentCommandOrBuilder.sendPromptOrNull: mrt.Mrt.SendPrompt?
  get() = if (hasSendPrompt()) getSendPrompt() else null

public val mrt.Mrt.AgentCommandOrBuilder.approvalResponseOrNull: mrt.Mrt.ApprovalResponse?
  get() = if (hasApprovalResponse()) getApprovalResponse() else null

public val mrt.Mrt.AgentCommandOrBuilder.cancelTaskOrNull: mrt.Mrt.CancelTask?
  get() = if (hasCancelTask()) getCancelTask() else null

public val mrt.Mrt.AgentCommandOrBuilder.getStatusOrNull: mrt.Mrt.GetStatus?
  get() = if (hasGetStatus()) getGetStatus() else null

