// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeapprovalResponse")
public inline fun approvalResponse(block: mrt.ApprovalResponseKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ApprovalResponse =
  mrt.ApprovalResponseKt.Dsl._create(mrt.Mrt.ApprovalResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ApprovalResponse`
 */
public object ApprovalResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ApprovalResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ApprovalResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ApprovalResponse = _builder.build()

    /**
     * ```
     * matches ApprovalRequest.approval_id
     * ```
     *
     * `string approval_id = 1;`
     */
    public var approvalId: kotlin.String
      @kotlin.jvm.JvmName("getApprovalId")
        get() = _builder.approvalId
      @kotlin.jvm.JvmName("setApprovalId")
        set(value) {
        _builder.approvalId = value
      }
    /**
     * ```
     * matches ApprovalRequest.approval_id
     * ```
     *
     * `string approval_id = 1;`
     */
    public fun clearApprovalId() {
      _builder.clearApprovalId()
    }

    /**
     * `bool approved = 2;`
     */
    public var approved: kotlin.Boolean
      @kotlin.jvm.JvmName("getApproved")
        get() = _builder.approved
      @kotlin.jvm.JvmName("setApproved")
        set(value) {
        _builder.approved = value
      }
    /**
     * `bool approved = 2;`
     */
    public fun clearApproved() {
      _builder.clearApproved()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ApprovalResponse.copy(block: `mrt`.ApprovalResponseKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ApprovalResponse =
  `mrt`.ApprovalResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

