// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeapprovalRequest")
public inline fun approvalRequest(block: mrt.ApprovalRequestKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ApprovalRequest =
  mrt.ApprovalRequestKt.Dsl._create(mrt.Mrt.ApprovalRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ApprovalRequest`
 */
public object ApprovalRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ApprovalRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ApprovalRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ApprovalRequest = _builder.build()

    /**
     * ```
     * unique ID for this request
     * ```
     *
     * `string approval_id = 1;`
     */
    public var approvalId: kotlin.String
      @kotlin.jvm.JvmName("getApprovalId")
        get() = _builder.approvalId
      @kotlin.jvm.JvmName("setApprovalId")
        set(value) {
        _builder.approvalId = value
      }
    /**
     * ```
     * unique ID for this request
     * ```
     *
     * `string approval_id = 1;`
     */
    public fun clearApprovalId() {
      _builder.clearApprovalId()
    }

    /**
     * `string session_id = 2;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 2;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * ```
     * human-readable: "Write to file auth.ts"
     * ```
     *
     * `string description = 3;`
     */
    public var description: kotlin.String
      @kotlin.jvm.JvmName("getDescription")
        get() = _builder.description
      @kotlin.jvm.JvmName("setDescription")
        set(value) {
        _builder.description = value
      }
    /**
     * ```
     * human-readable: "Write to file auth.ts"
     * ```
     *
     * `string description = 3;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * ```
     * actual command: "cat > auth.ts << 'EOF'..."
     * ```
     *
     * `string command = 4;`
     */
    public var command: kotlin.String
      @kotlin.jvm.JvmName("getCommand")
        get() = _builder.command
      @kotlin.jvm.JvmName("setCommand")
        set(value) {
        _builder.command = value
      }
    /**
     * ```
     * actual command: "cat > auth.ts << 'EOF'..."
     * ```
     *
     * `string command = 4;`
     */
    public fun clearCommand() {
      _builder.clearCommand()
    }

    /**
     * `.mrt.ApprovalType approval_type = 5;`
     */
    public var approvalType: mrt.Mrt.ApprovalType
      @kotlin.jvm.JvmName("getApprovalType")
        get() = _builder.approvalType
      @kotlin.jvm.JvmName("setApprovalType")
        set(value) {
        _builder.approvalType = value
      }
    public var approvalTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getApprovalTypeValue")
        get() = _builder.approvalTypeValue
      @kotlin.jvm.JvmName("setApprovalTypeValue")
        set(value) {
        _builder.approvalTypeValue = value
      }
    /**
     * `.mrt.ApprovalType approval_type = 5;`
     */
    public fun clearApprovalType() {
      _builder.clearApprovalType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ApprovalRequest.copy(block: `mrt`.ApprovalRequestKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ApprovalRequest =
  `mrt`.ApprovalRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

