// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializecloseSession")
public inline fun closeSession(block: mrt.CloseSessionKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CloseSession =
  mrt.CloseSessionKt.Dsl._create(mrt.Mrt.CloseSession.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.CloseSession`
 */
public object CloseSessionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.CloseSession.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.CloseSession.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.CloseSession = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.CloseSession.copy(block: `mrt`.CloseSessionKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CloseSession =
  `mrt`.CloseSessionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

