// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializecodexOutput")
public inline fun codexOutput(block: mrt.CodexOutputKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CodexOutput =
  mrt.CodexOutputKt.Dsl._create(mrt.Mrt.CodexOutput.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.CodexOutput`
 */
public object CodexOutputKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.CodexOutput.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.CodexOutput.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.CodexOutput = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * ```
     * text chunk (streaming)
     * ```
     *
     * `string content = 2;`
     */
    public var content: kotlin.String
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * ```
     * text chunk (streaming)
     * ```
     *
     * `string content = 2;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * ```
     * true = final chunk
     * ```
     *
     * `bool is_complete = 3;`
     */
    public var isComplete: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsComplete")
        get() = _builder.isComplete
      @kotlin.jvm.JvmName("setIsComplete")
        set(value) {
        _builder.isComplete = value
      }
    /**
     * ```
     * true = final chunk
     * ```
     *
     * `bool is_complete = 3;`
     */
    public fun clearIsComplete() {
      _builder.clearIsComplete()
    }

    /**
     * `.mrt.OutputType output_type = 4;`
     */
    public var outputType: mrt.Mrt.OutputType
      @kotlin.jvm.JvmName("getOutputType")
        get() = _builder.outputType
      @kotlin.jvm.JvmName("setOutputType")
        set(value) {
        _builder.outputType = value
      }
    public var outputTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getOutputTypeValue")
        get() = _builder.outputTypeValue
      @kotlin.jvm.JvmName("setOutputTypeValue")
        set(value) {
        _builder.outputTypeValue = value
      }
    /**
     * `.mrt.OutputType output_type = 4;`
     */
    public fun clearOutputType() {
      _builder.clearOutputType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.CodexOutput.copy(block: `mrt`.CodexOutputKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CodexOutput =
  `mrt`.CodexOutputKt.Dsl._create(this.toBuilder()).apply { block() }._build()

