// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeconnectToDevice")
public inline fun connectToDevice(block: mrt.ConnectToDeviceKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ConnectToDevice =
  mrt.ConnectToDeviceKt.Dsl._create(mrt.Mrt.ConnectToDevice.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ConnectToDevice`
 */
public object ConnectToDeviceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ConnectToDevice.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ConnectToDevice.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ConnectToDevice = _builder.build()

    /**
     * `string target_device_id = 1;`
     */
    public var targetDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getTargetDeviceId")
        get() = _builder.targetDeviceId
      @kotlin.jvm.JvmName("setTargetDeviceId")
        set(value) {
        _builder.targetDeviceId = value
      }
    /**
     * `string target_device_id = 1;`
     */
    public fun clearTargetDeviceId() {
      _builder.clearTargetDeviceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ConnectToDevice.copy(block: `mrt`.ConnectToDeviceKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ConnectToDevice =
  `mrt`.ConnectToDeviceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

