// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeconnectToDeviceAck")
public inline fun connectToDeviceAck(block: mrt.ConnectToDeviceAckKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ConnectToDeviceAck =
  mrt.ConnectToDeviceAckKt.Dsl._create(mrt.Mrt.ConnectToDeviceAck.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ConnectToDeviceAck`
 */
public object ConnectToDeviceAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ConnectToDeviceAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ConnectToDeviceAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ConnectToDeviceAck = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * ```
     * error reason if failed
     * ```
     *
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * error reason if failed
     * ```
     *
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `.mrt.ConnectionType connection_type = 3;`
     */
    public var connectionType: mrt.Mrt.ConnectionType
      @kotlin.jvm.JvmName("getConnectionType")
        get() = _builder.connectionType
      @kotlin.jvm.JvmName("setConnectionType")
        set(value) {
        _builder.connectionType = value
      }
    public var connectionTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getConnectionTypeValue")
        get() = _builder.connectionTypeValue
      @kotlin.jvm.JvmName("setConnectionTypeValue")
        set(value) {
        _builder.connectionTypeValue = value
      }
    /**
     * `.mrt.ConnectionType connection_type = 3;`
     */
    public fun clearConnectionType() {
      _builder.clearConnectionType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ConnectToDeviceAck.copy(block: `mrt`.ConnectToDeviceAckKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ConnectToDeviceAck =
  `mrt`.ConnectToDeviceAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

