// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializecreateDir")
public inline fun createDir(block: mrt.CreateDirKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CreateDir =
  mrt.CreateDirKt.Dsl._create(mrt.Mrt.CreateDir.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.CreateDir`
 */
public object CreateDirKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.CreateDir.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.CreateDir.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.CreateDir = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.CreateDir.copy(block: `mrt`.CreateDirKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CreateDir =
  `mrt`.CreateDirKt.Dsl._create(this.toBuilder()).apply { block() }._build()

