// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializecreateSession")
public inline fun createSession(block: mrt.CreateSessionKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CreateSession =
  mrt.CreateSessionKt.Dsl._create(mrt.Mrt.CreateSession.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.CreateSession`
 */
public object CreateSessionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.CreateSession.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.CreateSession.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.CreateSession = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string working_dir = 2;`
     */
    public var workingDir: kotlin.String
      @kotlin.jvm.JvmName("getWorkingDir")
        get() = _builder.workingDir
      @kotlin.jvm.JvmName("setWorkingDir")
        set(value) {
        _builder.workingDir = value
      }
    /**
     * `string working_dir = 2;`
     */
    public fun clearWorkingDir() {
      _builder.clearWorkingDir()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.CreateSession.copy(block: `mrt`.CreateSessionKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CreateSession =
  `mrt`.CreateSessionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

