// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializecreateFile")
public inline fun createFile(block: mrt.CreateFileKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CreateFile =
  mrt.CreateFileKt.Dsl._create(mrt.Mrt.CreateFile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.CreateFile`
 */
public object CreateFileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.CreateFile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.CreateFile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.CreateFile = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.CreateFile.copy(block: `mrt`.CreateFileKt.Dsl.() -> kotlin.Unit): mrt.Mrt.CreateFile =
  `mrt`.CreateFileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

