// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializedeletePath")
public inline fun deletePath(block: mrt.DeletePathKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeletePath =
  mrt.DeletePathKt.Dsl._create(mrt.Mrt.DeletePath.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.DeletePath`
 */
public object DeletePathKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.DeletePath.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.DeletePath.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.DeletePath = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `bool recursive = 2;`
     */
    public var recursive: kotlin.Boolean
      @kotlin.jvm.JvmName("getRecursive")
        get() = _builder.recursive
      @kotlin.jvm.JvmName("setRecursive")
        set(value) {
        _builder.recursive = value
      }
    /**
     * `bool recursive = 2;`
     */
    public fun clearRecursive() {
      _builder.clearRecursive()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.DeletePath.copy(block: `mrt`.DeletePathKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeletePath =
  `mrt`.DeletePathKt.Dsl._create(this.toBuilder()).apply { block() }._build()

