// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializedeviceInfo")
public inline fun deviceInfo(block: mrt.DeviceInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceInfo =
  mrt.DeviceInfoKt.Dsl._create(mrt.Mrt.DeviceInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.DeviceInfo`
 */
public object DeviceInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.DeviceInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.DeviceInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.DeviceInfo = _builder.build()

    /**
     * `string device_id = 1;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 1;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * `.mrt.DeviceType device_type = 2;`
     */
    public var deviceType: mrt.Mrt.DeviceType
      @kotlin.jvm.JvmName("getDeviceType")
        get() = _builder.deviceType
      @kotlin.jvm.JvmName("setDeviceType")
        set(value) {
        _builder.deviceType = value
      }
    public var deviceTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getDeviceTypeValue")
        get() = _builder.deviceTypeValue
      @kotlin.jvm.JvmName("setDeviceTypeValue")
        set(value) {
        _builder.deviceTypeValue = value
      }
    /**
     * `.mrt.DeviceType device_type = 2;`
     */
    public fun clearDeviceType() {
      _builder.clearDeviceType()
    }

    /**
     * `string display_name = 3;`
     */
    public var displayName: kotlin.String
      @kotlin.jvm.JvmName("getDisplayName")
        get() = _builder.displayName
      @kotlin.jvm.JvmName("setDisplayName")
        set(value) {
        _builder.displayName = value
      }
    /**
     * `string display_name = 3;`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }

    /**
     * `bool is_online = 4;`
     */
    public var isOnline: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsOnline")
        get() = _builder.isOnline
      @kotlin.jvm.JvmName("setIsOnline")
        set(value) {
        _builder.isOnline = value
      }
    /**
     * `bool is_online = 4;`
     */
    public fun clearIsOnline() {
      _builder.clearIsOnline()
    }

    /**
     * `uint64 last_seen_ms = 5;`
     */
    public var lastSeenMs: kotlin.Long
      @kotlin.jvm.JvmName("getLastSeenMs")
        get() = _builder.lastSeenMs
      @kotlin.jvm.JvmName("setLastSeenMs")
        set(value) {
        _builder.lastSeenMs = value
      }
    /**
     * `uint64 last_seen_ms = 5;`
     */
    public fun clearLastSeenMs() {
      _builder.clearLastSeenMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.DeviceInfo.copy(block: `mrt`.DeviceInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceInfo =
  `mrt`.DeviceInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

