// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializedeviceRegister")
public inline fun deviceRegister(block: mrt.DeviceRegisterKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceRegister =
  mrt.DeviceRegisterKt.Dsl._create(mrt.Mrt.DeviceRegister.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.DeviceRegister`
 */
public object DeviceRegisterKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.DeviceRegister.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.DeviceRegister.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.DeviceRegister = _builder.build()

    /**
     * `string device_id = 1;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 1;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * ```
     * per-user token (self-hosted) or JWT (managed)
     * ```
     *
     * `string auth_token = 2;`
     */
    public var authToken: kotlin.String
      @kotlin.jvm.JvmName("getAuthToken")
        get() = _builder.authToken
      @kotlin.jvm.JvmName("setAuthToken")
        set(value) {
        _builder.authToken = value
      }
    /**
     * ```
     * per-user token (self-hosted) or JWT (managed)
     * ```
     *
     * `string auth_token = 2;`
     */
    public fun clearAuthToken() {
      _builder.clearAuthToken()
    }

    /**
     * `.mrt.DeviceType device_type = 3;`
     */
    public var deviceType: mrt.Mrt.DeviceType
      @kotlin.jvm.JvmName("getDeviceType")
        get() = _builder.deviceType
      @kotlin.jvm.JvmName("setDeviceType")
        set(value) {
        _builder.deviceType = value
      }
    public var deviceTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getDeviceTypeValue")
        get() = _builder.deviceTypeValue
      @kotlin.jvm.JvmName("setDeviceTypeValue")
        set(value) {
        _builder.deviceTypeValue = value
      }
    /**
     * `.mrt.DeviceType device_type = 3;`
     */
    public fun clearDeviceType() {
      _builder.clearDeviceType()
    }

    /**
     * ```
     * "Ming's MacBook"
     * ```
     *
     * `string display_name = 4;`
     */
    public var displayName: kotlin.String
      @kotlin.jvm.JvmName("getDisplayName")
        get() = _builder.displayName
      @kotlin.jvm.JvmName("setDisplayName")
        set(value) {
        _builder.displayName = value
      }
    /**
     * ```
     * "Ming's MacBook"
     * ```
     *
     * `string display_name = 4;`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }

    /**
     * `string agent_version = 5;`
     */
    public var agentVersion: kotlin.String
      @kotlin.jvm.JvmName("getAgentVersion")
        get() = _builder.agentVersion
      @kotlin.jvm.JvmName("setAgentVersion")
        set(value) {
        _builder.agentVersion = value
      }
    /**
     * `string agent_version = 5;`
     */
    public fun clearAgentVersion() {
      _builder.clearAgentVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.DeviceRegister.copy(block: `mrt`.DeviceRegisterKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceRegister =
  `mrt`.DeviceRegisterKt.Dsl._create(this.toBuilder()).apply { block() }._build()

