// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializedeviceListResponse")
public inline fun deviceListResponse(block: mrt.DeviceListResponseKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceListResponse =
  mrt.DeviceListResponseKt.Dsl._create(mrt.Mrt.DeviceListResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.DeviceListResponse`
 */
public object DeviceListResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.DeviceListResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.DeviceListResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.DeviceListResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DevicesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .mrt.DeviceInfo devices = 1;`
     */
     public val devices: com.google.protobuf.kotlin.DslList<mrt.Mrt.DeviceInfo, DevicesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.devicesList
      )
    /**
     * `repeated .mrt.DeviceInfo devices = 1;`
     * @param value The devices to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addDevices")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.DeviceInfo, DevicesProxy>.add(value: mrt.Mrt.DeviceInfo) {
      _builder.addDevices(value)
    }
    /**
     * `repeated .mrt.DeviceInfo devices = 1;`
     * @param value The devices to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignDevices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.DeviceInfo, DevicesProxy>.plusAssign(value: mrt.Mrt.DeviceInfo) {
      add(value)
    }
    /**
     * `repeated .mrt.DeviceInfo devices = 1;`
     * @param values The devices to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllDevices")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.DeviceInfo, DevicesProxy>.addAll(values: kotlin.collections.Iterable<mrt.Mrt.DeviceInfo>) {
      _builder.addAllDevices(values)
    }
    /**
     * `repeated .mrt.DeviceInfo devices = 1;`
     * @param values The devices to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllDevices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.DeviceInfo, DevicesProxy>.plusAssign(values: kotlin.collections.Iterable<mrt.Mrt.DeviceInfo>) {
      addAll(values)
    }
    /**
     * `repeated .mrt.DeviceInfo devices = 1;`
     * @param index The index to set the value at.
     * @param value The devices to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDevices")
    public operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.DeviceInfo, DevicesProxy>.set(index: kotlin.Int, value: mrt.Mrt.DeviceInfo) {
      _builder.setDevices(index, value)
    }
    /**
     * `repeated .mrt.DeviceInfo devices = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDevices")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.DeviceInfo, DevicesProxy>.clear() {
      _builder.clearDevices()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.DeviceListResponse.copy(block: `mrt`.DeviceListResponseKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceListResponse =
  `mrt`.DeviceListResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

