// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializedeviceListRequest")
public inline fun deviceListRequest(block: mrt.DeviceListRequestKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceListRequest =
  mrt.DeviceListRequestKt.Dsl._create(mrt.Mrt.DeviceListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.DeviceListRequest`
 */
public object DeviceListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.DeviceListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.DeviceListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.DeviceListRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.DeviceListRequest.copy(block: `mrt`.DeviceListRequestKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DeviceListRequest =
  `mrt`.DeviceListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

