// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializedirListing")
public inline fun dirListing(block: mrt.DirListingKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DirListing =
  mrt.DirListingKt.Dsl._create(mrt.Mrt.DirListing.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.DirListing`
 */
public object DirListingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.DirListing.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.DirListing.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.DirListing = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EntriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .mrt.FileEntry entries = 1;`
     */
     public val entries: com.google.protobuf.kotlin.DslList<mrt.Mrt.FileEntry, EntriesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.entriesList
      )
    /**
     * `repeated .mrt.FileEntry entries = 1;`
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addEntries")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.FileEntry, EntriesProxy>.add(value: mrt.Mrt.FileEntry) {
      _builder.addEntries(value)
    }
    /**
     * `repeated .mrt.FileEntry entries = 1;`
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.FileEntry, EntriesProxy>.plusAssign(value: mrt.Mrt.FileEntry) {
      add(value)
    }
    /**
     * `repeated .mrt.FileEntry entries = 1;`
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllEntries")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.FileEntry, EntriesProxy>.addAll(values: kotlin.collections.Iterable<mrt.Mrt.FileEntry>) {
      _builder.addAllEntries(values)
    }
    /**
     * `repeated .mrt.FileEntry entries = 1;`
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.FileEntry, EntriesProxy>.plusAssign(values: kotlin.collections.Iterable<mrt.Mrt.FileEntry>) {
      addAll(values)
    }
    /**
     * `repeated .mrt.FileEntry entries = 1;`
     * @param index The index to set the value at.
     * @param value The entries to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEntries")
    public operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.FileEntry, EntriesProxy>.set(index: kotlin.Int, value: mrt.Mrt.FileEntry) {
      _builder.setEntries(index, value)
    }
    /**
     * `repeated .mrt.FileEntry entries = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearEntries")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.FileEntry, EntriesProxy>.clear() {
      _builder.clearEntries()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.DirListing.copy(block: `mrt`.DirListingKt.Dsl.() -> kotlin.Unit): mrt.Mrt.DirListing =
  `mrt`.DirListingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

