// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeenvelope")
public inline fun envelope(block: mrt.EnvelopeKt.Dsl.() -> kotlin.Unit): mrt.Mrt.Envelope =
  mrt.EnvelopeKt.Dsl._create(mrt.Mrt.Envelope.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.Envelope`
 */
public object EnvelopeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.Envelope.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.Envelope.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.Envelope = _builder.build()

    /**
     * ```
     * Current: 1. Increment on breaking changes.
     * ```
     *
     * `uint32 protocol_version = 1;`
     */
    public var protocolVersion: kotlin.Int
      @kotlin.jvm.JvmName("getProtocolVersion")
        get() = _builder.protocolVersion
      @kotlin.jvm.JvmName("setProtocolVersion")
        set(value) {
        _builder.protocolVersion = value
      }
    /**
     * ```
     * Current: 1. Increment on breaking changes.
     * ```
     *
     * `uint32 protocol_version = 1;`
     */
    public fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }

    /**
     * ```
     * UUID v4. Used to match request/response pairs.
     * ```
     *
     * `string request_id = 2;`
     */
    public var requestId: kotlin.String
      @kotlin.jvm.JvmName("getRequestId")
        get() = _builder.requestId
      @kotlin.jvm.JvmName("setRequestId")
        set(value) {
        _builder.requestId = value
      }
    /**
     * ```
     * UUID v4. Used to match request/response pairs.
     * ```
     *
     * `string request_id = 2;`
     */
    public fun clearRequestId() {
      _builder.clearRequestId()
    }

    /**
     * ```
     * Unix millis. Used for replay protection.
     * ```
     *
     * `uint64 timestamp_ms = 3;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * ```
     * Unix millis. Used for replay protection.
     * ```
     *
     * `uint64 timestamp_ms = 3;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }

    /**
     * `.mrt.Handshake handshake = 10;`
     */
    public var handshake: mrt.Mrt.Handshake
      @kotlin.jvm.JvmName("getHandshake")
        get() = _builder.handshake
      @kotlin.jvm.JvmName("setHandshake")
        set(value) {
        _builder.handshake = value
      }
    /**
     * `.mrt.Handshake handshake = 10;`
     */
    public fun clearHandshake() {
      _builder.clearHandshake()
    }
    /**
     * `.mrt.Handshake handshake = 10;`
     * @return Whether the handshake field is set.
     */
    public fun hasHandshake(): kotlin.Boolean {
      return _builder.hasHandshake()
    }

    /**
     * `.mrt.AgentCommand command = 11;`
     */
    public var command: mrt.Mrt.AgentCommand
      @kotlin.jvm.JvmName("getCommand")
        get() = _builder.command
      @kotlin.jvm.JvmName("setCommand")
        set(value) {
        _builder.command = value
      }
    /**
     * `.mrt.AgentCommand command = 11;`
     */
    public fun clearCommand() {
      _builder.clearCommand()
    }
    /**
     * `.mrt.AgentCommand command = 11;`
     * @return Whether the command field is set.
     */
    public fun hasCommand(): kotlin.Boolean {
      return _builder.hasCommand()
    }

    /**
     * `.mrt.AgentEvent event = 12;`
     */
    public var event: mrt.Mrt.AgentEvent
      @kotlin.jvm.JvmName("getEvent")
        get() = _builder.event
      @kotlin.jvm.JvmName("setEvent")
        set(value) {
        _builder.event = value
      }
    /**
     * `.mrt.AgentEvent event = 12;`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }
    /**
     * `.mrt.AgentEvent event = 12;`
     * @return Whether the event field is set.
     */
    public fun hasEvent(): kotlin.Boolean {
      return _builder.hasEvent()
    }

    /**
     * `.mrt.SessionControl session = 13;`
     */
    public var session: mrt.Mrt.SessionControl
      @kotlin.jvm.JvmName("getSession")
        get() = _builder.session
      @kotlin.jvm.JvmName("setSession")
        set(value) {
        _builder.session = value
      }
    /**
     * `.mrt.SessionControl session = 13;`
     */
    public fun clearSession() {
      _builder.clearSession()
    }
    /**
     * `.mrt.SessionControl session = 13;`
     * @return Whether the session field is set.
     */
    public fun hasSession(): kotlin.Boolean {
      return _builder.hasSession()
    }

    /**
     * `.mrt.FileOperation file_op = 14;`
     */
    public var fileOp: mrt.Mrt.FileOperation
      @kotlin.jvm.JvmName("getFileOp")
        get() = _builder.fileOp
      @kotlin.jvm.JvmName("setFileOp")
        set(value) {
        _builder.fileOp = value
      }
    /**
     * `.mrt.FileOperation file_op = 14;`
     */
    public fun clearFileOp() {
      _builder.clearFileOp()
    }
    /**
     * `.mrt.FileOperation file_op = 14;`
     * @return Whether the fileOp field is set.
     */
    public fun hasFileOp(): kotlin.Boolean {
      return _builder.hasFileOp()
    }

    /**
     * `.mrt.GitOperation git_op = 15;`
     */
    public var gitOp: mrt.Mrt.GitOperation
      @kotlin.jvm.JvmName("getGitOp")
        get() = _builder.gitOp
      @kotlin.jvm.JvmName("setGitOp")
        set(value) {
        _builder.gitOp = value
      }
    /**
     * `.mrt.GitOperation git_op = 15;`
     */
    public fun clearGitOp() {
      _builder.clearGitOp()
    }
    /**
     * `.mrt.GitOperation git_op = 15;`
     * @return Whether the gitOp field is set.
     */
    public fun hasGitOp(): kotlin.Boolean {
      return _builder.hasGitOp()
    }

    /**
     * `.mrt.FileResult file_result = 16;`
     */
    public var fileResult: mrt.Mrt.FileResult
      @kotlin.jvm.JvmName("getFileResult")
        get() = _builder.fileResult
      @kotlin.jvm.JvmName("setFileResult")
        set(value) {
        _builder.fileResult = value
      }
    /**
     * `.mrt.FileResult file_result = 16;`
     */
    public fun clearFileResult() {
      _builder.clearFileResult()
    }
    /**
     * `.mrt.FileResult file_result = 16;`
     * @return Whether the fileResult field is set.
     */
    public fun hasFileResult(): kotlin.Boolean {
      return _builder.hasFileResult()
    }

    /**
     * `.mrt.GitResult git_result = 17;`
     */
    public var gitResult: mrt.Mrt.GitResult
      @kotlin.jvm.JvmName("getGitResult")
        get() = _builder.gitResult
      @kotlin.jvm.JvmName("setGitResult")
        set(value) {
        _builder.gitResult = value
      }
    /**
     * `.mrt.GitResult git_result = 17;`
     */
    public fun clearGitResult() {
      _builder.clearGitResult()
    }
    /**
     * `.mrt.GitResult git_result = 17;`
     * @return Whether the gitResult field is set.
     */
    public fun hasGitResult(): kotlin.Boolean {
      return _builder.hasGitResult()
    }

    /**
     * `.mrt.Heartbeat heartbeat = 20;`
     */
    public var heartbeat: mrt.Mrt.Heartbeat
      @kotlin.jvm.JvmName("getHeartbeat")
        get() = _builder.heartbeat
      @kotlin.jvm.JvmName("setHeartbeat")
        set(value) {
        _builder.heartbeat = value
      }
    /**
     * `.mrt.Heartbeat heartbeat = 20;`
     */
    public fun clearHeartbeat() {
      _builder.clearHeartbeat()
    }
    /**
     * `.mrt.Heartbeat heartbeat = 20;`
     * @return Whether the heartbeat field is set.
     */
    public fun hasHeartbeat(): kotlin.Boolean {
      return _builder.hasHeartbeat()
    }

    /**
     * ```
     * Connection Node specific
     * ```
     *
     * `.mrt.DeviceRegister device_register = 30;`
     */
    public var deviceRegister: mrt.Mrt.DeviceRegister
      @kotlin.jvm.JvmName("getDeviceRegister")
        get() = _builder.deviceRegister
      @kotlin.jvm.JvmName("setDeviceRegister")
        set(value) {
        _builder.deviceRegister = value
      }
    /**
     * ```
     * Connection Node specific
     * ```
     *
     * `.mrt.DeviceRegister device_register = 30;`
     */
    public fun clearDeviceRegister() {
      _builder.clearDeviceRegister()
    }
    /**
     * ```
     * Connection Node specific
     * ```
     *
     * `.mrt.DeviceRegister device_register = 30;`
     * @return Whether the deviceRegister field is set.
     */
    public fun hasDeviceRegister(): kotlin.Boolean {
      return _builder.hasDeviceRegister()
    }

    /**
     * `.mrt.DeviceRegisterAck device_register_ack = 31;`
     */
    public var deviceRegisterAck: mrt.Mrt.DeviceRegisterAck
      @kotlin.jvm.JvmName("getDeviceRegisterAck")
        get() = _builder.deviceRegisterAck
      @kotlin.jvm.JvmName("setDeviceRegisterAck")
        set(value) {
        _builder.deviceRegisterAck = value
      }
    /**
     * `.mrt.DeviceRegisterAck device_register_ack = 31;`
     */
    public fun clearDeviceRegisterAck() {
      _builder.clearDeviceRegisterAck()
    }
    /**
     * `.mrt.DeviceRegisterAck device_register_ack = 31;`
     * @return Whether the deviceRegisterAck field is set.
     */
    public fun hasDeviceRegisterAck(): kotlin.Boolean {
      return _builder.hasDeviceRegisterAck()
    }

    /**
     * `.mrt.ConnectToDevice connect_to_device = 32;`
     */
    public var connectToDevice: mrt.Mrt.ConnectToDevice
      @kotlin.jvm.JvmName("getConnectToDevice")
        get() = _builder.connectToDevice
      @kotlin.jvm.JvmName("setConnectToDevice")
        set(value) {
        _builder.connectToDevice = value
      }
    /**
     * `.mrt.ConnectToDevice connect_to_device = 32;`
     */
    public fun clearConnectToDevice() {
      _builder.clearConnectToDevice()
    }
    /**
     * `.mrt.ConnectToDevice connect_to_device = 32;`
     * @return Whether the connectToDevice field is set.
     */
    public fun hasConnectToDevice(): kotlin.Boolean {
      return _builder.hasConnectToDevice()
    }

    /**
     * `.mrt.ConnectToDeviceAck connect_to_device_ack = 33;`
     */
    public var connectToDeviceAck: mrt.Mrt.ConnectToDeviceAck
      @kotlin.jvm.JvmName("getConnectToDeviceAck")
        get() = _builder.connectToDeviceAck
      @kotlin.jvm.JvmName("setConnectToDeviceAck")
        set(value) {
        _builder.connectToDeviceAck = value
      }
    /**
     * `.mrt.ConnectToDeviceAck connect_to_device_ack = 33;`
     */
    public fun clearConnectToDeviceAck() {
      _builder.clearConnectToDeviceAck()
    }
    /**
     * `.mrt.ConnectToDeviceAck connect_to_device_ack = 33;`
     * @return Whether the connectToDeviceAck field is set.
     */
    public fun hasConnectToDeviceAck(): kotlin.Boolean {
      return _builder.hasConnectToDeviceAck()
    }

    /**
     * `.mrt.DeviceListRequest device_list_request = 34;`
     */
    public var deviceListRequest: mrt.Mrt.DeviceListRequest
      @kotlin.jvm.JvmName("getDeviceListRequest")
        get() = _builder.deviceListRequest
      @kotlin.jvm.JvmName("setDeviceListRequest")
        set(value) {
        _builder.deviceListRequest = value
      }
    /**
     * `.mrt.DeviceListRequest device_list_request = 34;`
     */
    public fun clearDeviceListRequest() {
      _builder.clearDeviceListRequest()
    }
    /**
     * `.mrt.DeviceListRequest device_list_request = 34;`
     * @return Whether the deviceListRequest field is set.
     */
    public fun hasDeviceListRequest(): kotlin.Boolean {
      return _builder.hasDeviceListRequest()
    }

    /**
     * `.mrt.DeviceListResponse device_list_response = 35;`
     */
    public var deviceListResponse: mrt.Mrt.DeviceListResponse
      @kotlin.jvm.JvmName("getDeviceListResponse")
        get() = _builder.deviceListResponse
      @kotlin.jvm.JvmName("setDeviceListResponse")
        set(value) {
        _builder.deviceListResponse = value
      }
    /**
     * `.mrt.DeviceListResponse device_list_response = 35;`
     */
    public fun clearDeviceListResponse() {
      _builder.clearDeviceListResponse()
    }
    /**
     * `.mrt.DeviceListResponse device_list_response = 35;`
     * @return Whether the deviceListResponse field is set.
     */
    public fun hasDeviceListResponse(): kotlin.Boolean {
      return _builder.hasDeviceListResponse()
    }

    /**
     * ```
     * ICE signaling (managed mode)
     * ```
     *
     * `.mrt.IceCandidate ice_candidate = 40;`
     */
    public var iceCandidate: mrt.Mrt.IceCandidate
      @kotlin.jvm.JvmName("getIceCandidate")
        get() = _builder.iceCandidate
      @kotlin.jvm.JvmName("setIceCandidate")
        set(value) {
        _builder.iceCandidate = value
      }
    /**
     * ```
     * ICE signaling (managed mode)
     * ```
     *
     * `.mrt.IceCandidate ice_candidate = 40;`
     */
    public fun clearIceCandidate() {
      _builder.clearIceCandidate()
    }
    /**
     * ```
     * ICE signaling (managed mode)
     * ```
     *
     * `.mrt.IceCandidate ice_candidate = 40;`
     * @return Whether the iceCandidate field is set.
     */
    public fun hasIceCandidate(): kotlin.Boolean {
      return _builder.hasIceCandidate()
    }

    /**
     * `.mrt.IceOffer ice_offer = 41;`
     */
    public var iceOffer: mrt.Mrt.IceOffer
      @kotlin.jvm.JvmName("getIceOffer")
        get() = _builder.iceOffer
      @kotlin.jvm.JvmName("setIceOffer")
        set(value) {
        _builder.iceOffer = value
      }
    /**
     * `.mrt.IceOffer ice_offer = 41;`
     */
    public fun clearIceOffer() {
      _builder.clearIceOffer()
    }
    /**
     * `.mrt.IceOffer ice_offer = 41;`
     * @return Whether the iceOffer field is set.
     */
    public fun hasIceOffer(): kotlin.Boolean {
      return _builder.hasIceOffer()
    }

    /**
     * `.mrt.IceAnswer ice_answer = 42;`
     */
    public var iceAnswer: mrt.Mrt.IceAnswer
      @kotlin.jvm.JvmName("getIceAnswer")
        get() = _builder.iceAnswer
      @kotlin.jvm.JvmName("setIceAnswer")
        set(value) {
        _builder.iceAnswer = value
      }
    /**
     * `.mrt.IceAnswer ice_answer = 42;`
     */
    public fun clearIceAnswer() {
      _builder.clearIceAnswer()
    }
    /**
     * `.mrt.IceAnswer ice_answer = 42;`
     * @return Whether the iceAnswer field is set.
     */
    public fun hasIceAnswer(): kotlin.Boolean {
      return _builder.hasIceAnswer()
    }
    public val payloadCase: mrt.Mrt.Envelope.PayloadCase
    @kotlin.jvm.JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.Envelope.copy(block: `mrt`.EnvelopeKt.Dsl.() -> kotlin.Unit): mrt.Mrt.Envelope =
  `mrt`.EnvelopeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.EnvelopeOrBuilder.handshakeOrNull: mrt.Mrt.Handshake?
  get() = if (hasHandshake()) getHandshake() else null

public val mrt.Mrt.EnvelopeOrBuilder.commandOrNull: mrt.Mrt.AgentCommand?
  get() = if (hasCommand()) getCommand() else null

public val mrt.Mrt.EnvelopeOrBuilder.eventOrNull: mrt.Mrt.AgentEvent?
  get() = if (hasEvent()) getEvent() else null

public val mrt.Mrt.EnvelopeOrBuilder.sessionOrNull: mrt.Mrt.SessionControl?
  get() = if (hasSession()) getSession() else null

public val mrt.Mrt.EnvelopeOrBuilder.fileOpOrNull: mrt.Mrt.FileOperation?
  get() = if (hasFileOp()) getFileOp() else null

public val mrt.Mrt.EnvelopeOrBuilder.gitOpOrNull: mrt.Mrt.GitOperation?
  get() = if (hasGitOp()) getGitOp() else null

public val mrt.Mrt.EnvelopeOrBuilder.fileResultOrNull: mrt.Mrt.FileResult?
  get() = if (hasFileResult()) getFileResult() else null

public val mrt.Mrt.EnvelopeOrBuilder.gitResultOrNull: mrt.Mrt.GitResult?
  get() = if (hasGitResult()) getGitResult() else null

public val mrt.Mrt.EnvelopeOrBuilder.heartbeatOrNull: mrt.Mrt.Heartbeat?
  get() = if (hasHeartbeat()) getHeartbeat() else null

public val mrt.Mrt.EnvelopeOrBuilder.deviceRegisterOrNull: mrt.Mrt.DeviceRegister?
  get() = if (hasDeviceRegister()) getDeviceRegister() else null

public val mrt.Mrt.EnvelopeOrBuilder.deviceRegisterAckOrNull: mrt.Mrt.DeviceRegisterAck?
  get() = if (hasDeviceRegisterAck()) getDeviceRegisterAck() else null

public val mrt.Mrt.EnvelopeOrBuilder.connectToDeviceOrNull: mrt.Mrt.ConnectToDevice?
  get() = if (hasConnectToDevice()) getConnectToDevice() else null

public val mrt.Mrt.EnvelopeOrBuilder.connectToDeviceAckOrNull: mrt.Mrt.ConnectToDeviceAck?
  get() = if (hasConnectToDeviceAck()) getConnectToDeviceAck() else null

public val mrt.Mrt.EnvelopeOrBuilder.deviceListRequestOrNull: mrt.Mrt.DeviceListRequest?
  get() = if (hasDeviceListRequest()) getDeviceListRequest() else null

public val mrt.Mrt.EnvelopeOrBuilder.deviceListResponseOrNull: mrt.Mrt.DeviceListResponse?
  get() = if (hasDeviceListResponse()) getDeviceListResponse() else null

public val mrt.Mrt.EnvelopeOrBuilder.iceCandidateOrNull: mrt.Mrt.IceCandidate?
  get() = if (hasIceCandidate()) getIceCandidate() else null

public val mrt.Mrt.EnvelopeOrBuilder.iceOfferOrNull: mrt.Mrt.IceOffer?
  get() = if (hasIceOffer()) getIceOffer() else null

public val mrt.Mrt.EnvelopeOrBuilder.iceAnswerOrNull: mrt.Mrt.IceAnswer?
  get() = if (hasIceAnswer()) getIceAnswer() else null

