// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeerrorEvent")
public inline fun errorEvent(block: mrt.ErrorEventKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ErrorEvent =
  mrt.ErrorEventKt.Dsl._create(mrt.Mrt.ErrorEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ErrorEvent`
 */
public object ErrorEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ErrorEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ErrorEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ErrorEvent = _builder.build()

    /**
     * ```
     * e.g. "VERSION_MISMATCH", "AUTH_FAILED", "CODEX_UNAVAILABLE"
     * ```
     *
     * `string code = 1;`
     */
    public var code: kotlin.String
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * ```
     * e.g. "VERSION_MISMATCH", "AUTH_FAILED", "CODEX_UNAVAILABLE"
     * ```
     *
     * `string code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * if true, connection will be closed
     * ```
     *
     * `bool fatal = 3;`
     */
    public var fatal: kotlin.Boolean
      @kotlin.jvm.JvmName("getFatal")
        get() = _builder.fatal
      @kotlin.jvm.JvmName("setFatal")
        set(value) {
        _builder.fatal = value
      }
    /**
     * ```
     * if true, connection will be closed
     * ```
     *
     * `bool fatal = 3;`
     */
    public fun clearFatal() {
      _builder.clearFatal()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ErrorEvent.copy(block: `mrt`.ErrorEventKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ErrorEvent =
  `mrt`.ErrorEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

