// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializefileOperation")
public inline fun fileOperation(block: mrt.FileOperationKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileOperation =
  mrt.FileOperationKt.Dsl._create(mrt.Mrt.FileOperation.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.FileOperation`
 */
public object FileOperationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.FileOperation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.FileOperation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.FileOperation = _builder.build()

    /**
     * ```
     * scope to session's working_dir
     * ```
     *
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * ```
     * scope to session's working_dir
     * ```
     *
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `.mrt.ListDir list_dir = 2;`
     */
    public var listDir: mrt.Mrt.ListDir
      @kotlin.jvm.JvmName("getListDir")
        get() = _builder.listDir
      @kotlin.jvm.JvmName("setListDir")
        set(value) {
        _builder.listDir = value
      }
    /**
     * `.mrt.ListDir list_dir = 2;`
     */
    public fun clearListDir() {
      _builder.clearListDir()
    }
    /**
     * `.mrt.ListDir list_dir = 2;`
     * @return Whether the listDir field is set.
     */
    public fun hasListDir(): kotlin.Boolean {
      return _builder.hasListDir()
    }

    /**
     * `.mrt.ReadFile read_file = 3;`
     */
    public var readFile: mrt.Mrt.ReadFile
      @kotlin.jvm.JvmName("getReadFile")
        get() = _builder.readFile
      @kotlin.jvm.JvmName("setReadFile")
        set(value) {
        _builder.readFile = value
      }
    /**
     * `.mrt.ReadFile read_file = 3;`
     */
    public fun clearReadFile() {
      _builder.clearReadFile()
    }
    /**
     * `.mrt.ReadFile read_file = 3;`
     * @return Whether the readFile field is set.
     */
    public fun hasReadFile(): kotlin.Boolean {
      return _builder.hasReadFile()
    }

    /**
     * `.mrt.WriteFile write_file = 4;`
     */
    public var writeFile: mrt.Mrt.WriteFile
      @kotlin.jvm.JvmName("getWriteFile")
        get() = _builder.writeFile
      @kotlin.jvm.JvmName("setWriteFile")
        set(value) {
        _builder.writeFile = value
      }
    /**
     * `.mrt.WriteFile write_file = 4;`
     */
    public fun clearWriteFile() {
      _builder.clearWriteFile()
    }
    /**
     * `.mrt.WriteFile write_file = 4;`
     * @return Whether the writeFile field is set.
     */
    public fun hasWriteFile(): kotlin.Boolean {
      return _builder.hasWriteFile()
    }

    /**
     * `.mrt.CreateFile create_file = 5;`
     */
    public var createFile: mrt.Mrt.CreateFile
      @kotlin.jvm.JvmName("getCreateFile")
        get() = _builder.createFile
      @kotlin.jvm.JvmName("setCreateFile")
        set(value) {
        _builder.createFile = value
      }
    /**
     * `.mrt.CreateFile create_file = 5;`
     */
    public fun clearCreateFile() {
      _builder.clearCreateFile()
    }
    /**
     * `.mrt.CreateFile create_file = 5;`
     * @return Whether the createFile field is set.
     */
    public fun hasCreateFile(): kotlin.Boolean {
      return _builder.hasCreateFile()
    }

    /**
     * `.mrt.CreateDir create_dir = 6;`
     */
    public var createDir: mrt.Mrt.CreateDir
      @kotlin.jvm.JvmName("getCreateDir")
        get() = _builder.createDir
      @kotlin.jvm.JvmName("setCreateDir")
        set(value) {
        _builder.createDir = value
      }
    /**
     * `.mrt.CreateDir create_dir = 6;`
     */
    public fun clearCreateDir() {
      _builder.clearCreateDir()
    }
    /**
     * `.mrt.CreateDir create_dir = 6;`
     * @return Whether the createDir field is set.
     */
    public fun hasCreateDir(): kotlin.Boolean {
      return _builder.hasCreateDir()
    }

    /**
     * `.mrt.DeletePath delete_path = 7;`
     */
    public var deletePath: mrt.Mrt.DeletePath
      @kotlin.jvm.JvmName("getDeletePath")
        get() = _builder.deletePath
      @kotlin.jvm.JvmName("setDeletePath")
        set(value) {
        _builder.deletePath = value
      }
    /**
     * `.mrt.DeletePath delete_path = 7;`
     */
    public fun clearDeletePath() {
      _builder.clearDeletePath()
    }
    /**
     * `.mrt.DeletePath delete_path = 7;`
     * @return Whether the deletePath field is set.
     */
    public fun hasDeletePath(): kotlin.Boolean {
      return _builder.hasDeletePath()
    }

    /**
     * `.mrt.RenamePath rename_path = 8;`
     */
    public var renamePath: mrt.Mrt.RenamePath
      @kotlin.jvm.JvmName("getRenamePath")
        get() = _builder.renamePath
      @kotlin.jvm.JvmName("setRenamePath")
        set(value) {
        _builder.renamePath = value
      }
    /**
     * `.mrt.RenamePath rename_path = 8;`
     */
    public fun clearRenamePath() {
      _builder.clearRenamePath()
    }
    /**
     * `.mrt.RenamePath rename_path = 8;`
     * @return Whether the renamePath field is set.
     */
    public fun hasRenamePath(): kotlin.Boolean {
      return _builder.hasRenamePath()
    }
    public val opCase: mrt.Mrt.FileOperation.OpCase
    @kotlin.jvm.JvmName("getOpCase")
      get() = _builder.getOpCase()

    public fun clearOp() {
      _builder.clearOp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.FileOperation.copy(block: `mrt`.FileOperationKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileOperation =
  `mrt`.FileOperationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.FileOperationOrBuilder.listDirOrNull: mrt.Mrt.ListDir?
  get() = if (hasListDir()) getListDir() else null

public val mrt.Mrt.FileOperationOrBuilder.readFileOrNull: mrt.Mrt.ReadFile?
  get() = if (hasReadFile()) getReadFile() else null

public val mrt.Mrt.FileOperationOrBuilder.writeFileOrNull: mrt.Mrt.WriteFile?
  get() = if (hasWriteFile()) getWriteFile() else null

public val mrt.Mrt.FileOperationOrBuilder.createFileOrNull: mrt.Mrt.CreateFile?
  get() = if (hasCreateFile()) getCreateFile() else null

public val mrt.Mrt.FileOperationOrBuilder.createDirOrNull: mrt.Mrt.CreateDir?
  get() = if (hasCreateDir()) getCreateDir() else null

public val mrt.Mrt.FileOperationOrBuilder.deletePathOrNull: mrt.Mrt.DeletePath?
  get() = if (hasDeletePath()) getDeletePath() else null

public val mrt.Mrt.FileOperationOrBuilder.renamePathOrNull: mrt.Mrt.RenamePath?
  get() = if (hasRenamePath()) getRenamePath() else null

