// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializefileEntry")
public inline fun fileEntry(block: mrt.FileEntryKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileEntry =
  mrt.FileEntryKt.Dsl._create(mrt.Mrt.FileEntry.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.FileEntry`
 */
public object FileEntryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.FileEntry.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.FileEntry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.FileEntry = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string path = 2;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 2;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `bool is_dir = 3;`
     */
    public var isDir: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsDir")
        get() = _builder.isDir
      @kotlin.jvm.JvmName("setIsDir")
        set(value) {
        _builder.isDir = value
      }
    /**
     * `bool is_dir = 3;`
     */
    public fun clearIsDir() {
      _builder.clearIsDir()
    }

    /**
     * `uint64 size = 4;`
     */
    public var size: kotlin.Long
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `uint64 size = 4;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }

    /**
     * `uint64 modified_ms = 5;`
     */
    public var modifiedMs: kotlin.Long
      @kotlin.jvm.JvmName("getModifiedMs")
        get() = _builder.modifiedMs
      @kotlin.jvm.JvmName("setModifiedMs")
        set(value) {
        _builder.modifiedMs = value
      }
    /**
     * `uint64 modified_ms = 5;`
     */
    public fun clearModifiedMs() {
      _builder.clearModifiedMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.FileEntry.copy(block: `mrt`.FileEntryKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileEntry =
  `mrt`.FileEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

