// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializefileWriteAck")
public inline fun fileWriteAck(block: mrt.FileWriteAckKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileWriteAck =
  mrt.FileWriteAckKt.Dsl._create(mrt.Mrt.FileWriteAck.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.FileWriteAck`
 */
public object FileWriteAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.FileWriteAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.FileWriteAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.FileWriteAck = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `bool success = 2;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 2;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.FileWriteAck.copy(block: `mrt`.FileWriteAckKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileWriteAck =
  `mrt`.FileWriteAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

