// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializefileResult")
public inline fun fileResult(block: mrt.FileResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileResult =
  mrt.FileResultKt.Dsl._create(mrt.Mrt.FileResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.FileResult`
 */
public object FileResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.FileResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.FileResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.FileResult = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `.mrt.DirListing dir_listing = 2;`
     */
    public var dirListing: mrt.Mrt.DirListing
      @kotlin.jvm.JvmName("getDirListing")
        get() = _builder.dirListing
      @kotlin.jvm.JvmName("setDirListing")
        set(value) {
        _builder.dirListing = value
      }
    /**
     * `.mrt.DirListing dir_listing = 2;`
     */
    public fun clearDirListing() {
      _builder.clearDirListing()
    }
    /**
     * `.mrt.DirListing dir_listing = 2;`
     * @return Whether the dirListing field is set.
     */
    public fun hasDirListing(): kotlin.Boolean {
      return _builder.hasDirListing()
    }

    /**
     * `.mrt.FileContent file_content = 3;`
     */
    public var fileContent: mrt.Mrt.FileContent
      @kotlin.jvm.JvmName("getFileContent")
        get() = _builder.fileContent
      @kotlin.jvm.JvmName("setFileContent")
        set(value) {
        _builder.fileContent = value
      }
    /**
     * `.mrt.FileContent file_content = 3;`
     */
    public fun clearFileContent() {
      _builder.clearFileContent()
    }
    /**
     * `.mrt.FileContent file_content = 3;`
     * @return Whether the fileContent field is set.
     */
    public fun hasFileContent(): kotlin.Boolean {
      return _builder.hasFileContent()
    }

    /**
     * `.mrt.FileWriteAck write_ack = 4;`
     */
    public var writeAck: mrt.Mrt.FileWriteAck
      @kotlin.jvm.JvmName("getWriteAck")
        get() = _builder.writeAck
      @kotlin.jvm.JvmName("setWriteAck")
        set(value) {
        _builder.writeAck = value
      }
    /**
     * `.mrt.FileWriteAck write_ack = 4;`
     */
    public fun clearWriteAck() {
      _builder.clearWriteAck()
    }
    /**
     * `.mrt.FileWriteAck write_ack = 4;`
     * @return Whether the writeAck field is set.
     */
    public fun hasWriteAck(): kotlin.Boolean {
      return _builder.hasWriteAck()
    }

    /**
     * `.mrt.ErrorEvent error = 10;`
     */
    public var error: mrt.Mrt.ErrorEvent
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.mrt.ErrorEvent error = 10;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.mrt.ErrorEvent error = 10;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }
    public val resultCase: mrt.Mrt.FileResult.ResultCase
    @kotlin.jvm.JvmName("getResultCase")
      get() = _builder.getResultCase()

    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.FileResult.copy(block: `mrt`.FileResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileResult =
  `mrt`.FileResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.FileResultOrBuilder.dirListingOrNull: mrt.Mrt.DirListing?
  get() = if (hasDirListing()) getDirListing() else null

public val mrt.Mrt.FileResultOrBuilder.fileContentOrNull: mrt.Mrt.FileContent?
  get() = if (hasFileContent()) getFileContent() else null

public val mrt.Mrt.FileResultOrBuilder.writeAckOrNull: mrt.Mrt.FileWriteAck?
  get() = if (hasWriteAck()) getWriteAck() else null

public val mrt.Mrt.FileResultOrBuilder.errorOrNull: mrt.Mrt.ErrorEvent?
  get() = if (hasError()) getError() else null

