// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializefileContent")
public inline fun fileContent(block: mrt.FileContentKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileContent =
  mrt.FileContentKt.Dsl._create(mrt.Mrt.FileContent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.FileContent`
 */
public object FileContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.FileContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.FileContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.FileContent = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `bytes content = 2;`
     */
    public var content: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `bytes content = 2;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * `string mime_type = 3;`
     */
    public var mimeType: kotlin.String
      @kotlin.jvm.JvmName("getMimeType")
        get() = _builder.mimeType
      @kotlin.jvm.JvmName("setMimeType")
        set(value) {
        _builder.mimeType = value
      }
    /**
     * `string mime_type = 3;`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.FileContent.copy(block: `mrt`.FileContentKt.Dsl.() -> kotlin.Unit): mrt.Mrt.FileContent =
  `mrt`.FileContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

