// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegetStatus")
public inline fun getStatus(block: mrt.GetStatusKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GetStatus =
  mrt.GetStatusKt.Dsl._create(mrt.Mrt.GetStatus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GetStatus`
 */
public object GetStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GetStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GetStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GetStatus = _builder.build()

    /**
     * ```
     * empty = get all sessions
     * ```
     *
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * ```
     * empty = get all sessions
     * ```
     *
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GetStatus.copy(block: `mrt`.GetStatusKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GetStatus =
  `mrt`.GetStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

