// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitBranchesResult")
public inline fun gitBranchesResult(block: mrt.GitBranchesResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitBranchesResult =
  mrt.GitBranchesResultKt.Dsl._create(mrt.Mrt.GitBranchesResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitBranchesResult`
 */
public object GitBranchesResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitBranchesResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitBranchesResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitBranchesResult = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class BranchesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string branches = 1;`
     * @return A list containing the branches.
     */
    public val branches: com.google.protobuf.kotlin.DslList<kotlin.String, BranchesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.branchesList
      )
    /**
     * `repeated string branches = 1;`
     * @param value The branches to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addBranches")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, BranchesProxy>.add(value: kotlin.String) {
      _builder.addBranches(value)
    }
    /**
     * `repeated string branches = 1;`
     * @param value The branches to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignBranches")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, BranchesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string branches = 1;`
     * @param values The branches to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllBranches")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, BranchesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllBranches(values)
    }
    /**
     * `repeated string branches = 1;`
     * @param values The branches to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllBranches")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, BranchesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string branches = 1;`
     * @param index The index to set the value at.
     * @param value The branches to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setBranches")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, BranchesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setBranches(index, value)
    }/**
     * `repeated string branches = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setBranches")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, BranchesProxy>.clear() {
      _builder.clearBranches()
    }
    /**
     * `string current = 2;`
     */
    public var current: kotlin.String
      @kotlin.jvm.JvmName("getCurrent")
        get() = _builder.current
      @kotlin.jvm.JvmName("setCurrent")
        set(value) {
        _builder.current = value
      }
    /**
     * `string current = 2;`
     */
    public fun clearCurrent() {
      _builder.clearCurrent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitBranchesResult.copy(block: `mrt`.GitBranchesResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitBranchesResult =
  `mrt`.GitBranchesResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

