// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitBranchesReq")
public inline fun gitBranchesReq(block: mrt.GitBranchesReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitBranchesReq =
  mrt.GitBranchesReqKt.Dsl._create(mrt.Mrt.GitBranchesReq.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitBranchesReq`
 */
public object GitBranchesReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitBranchesReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitBranchesReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitBranchesReq = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitBranchesReq.copy(block: `mrt`.GitBranchesReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitBranchesReq =
  `mrt`.GitBranchesReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

