// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitCommitInfo")
public inline fun gitCommitInfo(block: mrt.GitCommitInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitCommitInfo =
  mrt.GitCommitInfoKt.Dsl._create(mrt.Mrt.GitCommitInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitCommitInfo`
 */
public object GitCommitInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitCommitInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitCommitInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitCommitInfo = _builder.build()

    /**
     * `string hash = 1;`
     */
    public var hash: kotlin.String
      @kotlin.jvm.JvmName("getHash")
        get() = _builder.hash
      @kotlin.jvm.JvmName("setHash")
        set(value) {
        _builder.hash = value
      }
    /**
     * `string hash = 1;`
     */
    public fun clearHash() {
      _builder.clearHash()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `string author = 3;`
     */
    public var author: kotlin.String
      @kotlin.jvm.JvmName("getAuthor")
        get() = _builder.author
      @kotlin.jvm.JvmName("setAuthor")
        set(value) {
        _builder.author = value
      }
    /**
     * `string author = 3;`
     */
    public fun clearAuthor() {
      _builder.clearAuthor()
    }

    /**
     * `uint64 timestamp_ms = 4;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `uint64 timestamp_ms = 4;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitCommitInfo.copy(block: `mrt`.GitCommitInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitCommitInfo =
  `mrt`.GitCommitInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

