// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitCommitReq")
public inline fun gitCommitReq(block: mrt.GitCommitReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitCommitReq =
  mrt.GitCommitReqKt.Dsl._create(mrt.Mrt.GitCommitReq.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitCommitReq`
 */
public object GitCommitReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitCommitReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitCommitReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitCommitReq = _builder.build()

    /**
     * `string message = 1;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `bool stage_all = 2;`
     */
    public var stageAll: kotlin.Boolean
      @kotlin.jvm.JvmName("getStageAll")
        get() = _builder.stageAll
      @kotlin.jvm.JvmName("setStageAll")
        set(value) {
        _builder.stageAll = value
      }
    /**
     * `bool stage_all = 2;`
     */
    public fun clearStageAll() {
      _builder.clearStageAll()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitCommitReq.copy(block: `mrt`.GitCommitReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitCommitReq =
  `mrt`.GitCommitReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

