// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitCheckoutReq")
public inline fun gitCheckoutReq(block: mrt.GitCheckoutReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitCheckoutReq =
  mrt.GitCheckoutReqKt.Dsl._create(mrt.Mrt.GitCheckoutReq.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitCheckoutReq`
 */
public object GitCheckoutReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitCheckoutReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitCheckoutReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitCheckoutReq = _builder.build()

    /**
     * `string branch = 1;`
     */
    public var branch: kotlin.String
      @kotlin.jvm.JvmName("getBranch")
        get() = _builder.branch
      @kotlin.jvm.JvmName("setBranch")
        set(value) {
        _builder.branch = value
      }
    /**
     * `string branch = 1;`
     */
    public fun clearBranch() {
      _builder.clearBranch()
    }

    /**
     * `bool create = 2;`
     */
    public var create: kotlin.Boolean
      @kotlin.jvm.JvmName("getCreate")
        get() = _builder.create
      @kotlin.jvm.JvmName("setCreate")
        set(value) {
        _builder.create = value
      }
    /**
     * `bool create = 2;`
     */
    public fun clearCreate() {
      _builder.clearCreate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitCheckoutReq.copy(block: `mrt`.GitCheckoutReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitCheckoutReq =
  `mrt`.GitCheckoutReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

