// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitDiffReq")
public inline fun gitDiffReq(block: mrt.GitDiffReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitDiffReq =
  mrt.GitDiffReqKt.Dsl._create(mrt.Mrt.GitDiffReq.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitDiffReq`
 */
public object GitDiffReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitDiffReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitDiffReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitDiffReq = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `bool staged = 2;`
     */
    public var staged: kotlin.Boolean
      @kotlin.jvm.JvmName("getStaged")
        get() = _builder.staged
      @kotlin.jvm.JvmName("setStaged")
        set(value) {
        _builder.staged = value
      }
    /**
     * `bool staged = 2;`
     */
    public fun clearStaged() {
      _builder.clearStaged()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitDiffReq.copy(block: `mrt`.GitDiffReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitDiffReq =
  `mrt`.GitDiffReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

