// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitDiffResult")
public inline fun gitDiffResult(block: mrt.GitDiffResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitDiffResult =
  mrt.GitDiffResultKt.Dsl._create(mrt.Mrt.GitDiffResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitDiffResult`
 */
public object GitDiffResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitDiffResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitDiffResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitDiffResult = _builder.build()

    /**
     * `string diff = 1;`
     */
    public var diff: kotlin.String
      @kotlin.jvm.JvmName("getDiff")
        get() = _builder.diff
      @kotlin.jvm.JvmName("setDiff")
        set(value) {
        _builder.diff = value
      }
    /**
     * `string diff = 1;`
     */
    public fun clearDiff() {
      _builder.clearDiff()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitDiffResult.copy(block: `mrt`.GitDiffResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitDiffResult =
  `mrt`.GitDiffResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

