// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitFileChange")
public inline fun gitFileChange(block: mrt.GitFileChangeKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitFileChange =
  mrt.GitFileChangeKt.Dsl._create(mrt.Mrt.GitFileChange.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitFileChange`
 */
public object GitFileChangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitFileChange.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitFileChange.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitFileChange = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * ```
     * "modified", "added", "deleted", "untracked"
     * ```
     *
     * `string status = 2;`
     */
    public var status: kotlin.String
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * ```
     * "modified", "added", "deleted", "untracked"
     * ```
     *
     * `string status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitFileChange.copy(block: `mrt`.GitFileChangeKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitFileChange =
  `mrt`.GitFileChangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

