// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitLogReq")
public inline fun gitLogReq(block: mrt.GitLogReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitLogReq =
  mrt.GitLogReqKt.Dsl._create(mrt.Mrt.GitLogReq.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitLogReq`
 */
public object GitLogReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitLogReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitLogReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitLogReq = _builder.build()

    /**
     * `uint32 limit = 1;`
     */
    public var limit: kotlin.Int
      @kotlin.jvm.JvmName("getLimit")
        get() = _builder.limit
      @kotlin.jvm.JvmName("setLimit")
        set(value) {
        _builder.limit = value
      }
    /**
     * `uint32 limit = 1;`
     */
    public fun clearLimit() {
      _builder.clearLimit()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitLogReq.copy(block: `mrt`.GitLogReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitLogReq =
  `mrt`.GitLogReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

