// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitLogResult")
public inline fun gitLogResult(block: mrt.GitLogResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitLogResult =
  mrt.GitLogResultKt.Dsl._create(mrt.Mrt.GitLogResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitLogResult`
 */
public object GitLogResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitLogResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitLogResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitLogResult = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CommitsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .mrt.GitCommitInfo commits = 1;`
     */
     public val commits: com.google.protobuf.kotlin.DslList<mrt.Mrt.GitCommitInfo, CommitsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.commitsList
      )
    /**
     * `repeated .mrt.GitCommitInfo commits = 1;`
     * @param value The commits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addCommits")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitCommitInfo, CommitsProxy>.add(value: mrt.Mrt.GitCommitInfo) {
      _builder.addCommits(value)
    }
    /**
     * `repeated .mrt.GitCommitInfo commits = 1;`
     * @param value The commits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignCommits")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitCommitInfo, CommitsProxy>.plusAssign(value: mrt.Mrt.GitCommitInfo) {
      add(value)
    }
    /**
     * `repeated .mrt.GitCommitInfo commits = 1;`
     * @param values The commits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllCommits")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitCommitInfo, CommitsProxy>.addAll(values: kotlin.collections.Iterable<mrt.Mrt.GitCommitInfo>) {
      _builder.addAllCommits(values)
    }
    /**
     * `repeated .mrt.GitCommitInfo commits = 1;`
     * @param values The commits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllCommits")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitCommitInfo, CommitsProxy>.plusAssign(values: kotlin.collections.Iterable<mrt.Mrt.GitCommitInfo>) {
      addAll(values)
    }
    /**
     * `repeated .mrt.GitCommitInfo commits = 1;`
     * @param index The index to set the value at.
     * @param value The commits to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCommits")
    public operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitCommitInfo, CommitsProxy>.set(index: kotlin.Int, value: mrt.Mrt.GitCommitInfo) {
      _builder.setCommits(index, value)
    }
    /**
     * `repeated .mrt.GitCommitInfo commits = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearCommits")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitCommitInfo, CommitsProxy>.clear() {
      _builder.clearCommits()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitLogResult.copy(block: `mrt`.GitLogResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitLogResult =
  `mrt`.GitLogResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

