// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitOperation")
public inline fun gitOperation(block: mrt.GitOperationKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitOperation =
  mrt.GitOperationKt.Dsl._create(mrt.Mrt.GitOperation.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitOperation`
 */
public object GitOperationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitOperation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitOperation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitOperation = _builder.build()

    /**
     * ```
     * scope to session's working_dir
     * ```
     *
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * ```
     * scope to session's working_dir
     * ```
     *
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `.mrt.GitStatusReq status = 2;`
     */
    public var status: mrt.Mrt.GitStatusReq
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * `.mrt.GitStatusReq status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * `.mrt.GitStatusReq status = 2;`
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * `.mrt.GitCommitReq commit = 3;`
     */
    public var commit: mrt.Mrt.GitCommitReq
      @kotlin.jvm.JvmName("getCommit")
        get() = _builder.commit
      @kotlin.jvm.JvmName("setCommit")
        set(value) {
        _builder.commit = value
      }
    /**
     * `.mrt.GitCommitReq commit = 3;`
     */
    public fun clearCommit() {
      _builder.clearCommit()
    }
    /**
     * `.mrt.GitCommitReq commit = 3;`
     * @return Whether the commit field is set.
     */
    public fun hasCommit(): kotlin.Boolean {
      return _builder.hasCommit()
    }

    /**
     * `.mrt.GitPushReq push = 4;`
     */
    public var push: mrt.Mrt.GitPushReq
      @kotlin.jvm.JvmName("getPush")
        get() = _builder.push
      @kotlin.jvm.JvmName("setPush")
        set(value) {
        _builder.push = value
      }
    /**
     * `.mrt.GitPushReq push = 4;`
     */
    public fun clearPush() {
      _builder.clearPush()
    }
    /**
     * `.mrt.GitPushReq push = 4;`
     * @return Whether the push field is set.
     */
    public fun hasPush(): kotlin.Boolean {
      return _builder.hasPush()
    }

    /**
     * `.mrt.GitPullReq pull = 5;`
     */
    public var pull: mrt.Mrt.GitPullReq
      @kotlin.jvm.JvmName("getPull")
        get() = _builder.pull
      @kotlin.jvm.JvmName("setPull")
        set(value) {
        _builder.pull = value
      }
    /**
     * `.mrt.GitPullReq pull = 5;`
     */
    public fun clearPull() {
      _builder.clearPull()
    }
    /**
     * `.mrt.GitPullReq pull = 5;`
     * @return Whether the pull field is set.
     */
    public fun hasPull(): kotlin.Boolean {
      return _builder.hasPull()
    }

    /**
     * `.mrt.GitDiffReq diff = 6;`
     */
    public var diff: mrt.Mrt.GitDiffReq
      @kotlin.jvm.JvmName("getDiff")
        get() = _builder.diff
      @kotlin.jvm.JvmName("setDiff")
        set(value) {
        _builder.diff = value
      }
    /**
     * `.mrt.GitDiffReq diff = 6;`
     */
    public fun clearDiff() {
      _builder.clearDiff()
    }
    /**
     * `.mrt.GitDiffReq diff = 6;`
     * @return Whether the diff field is set.
     */
    public fun hasDiff(): kotlin.Boolean {
      return _builder.hasDiff()
    }

    /**
     * `.mrt.GitLogReq log = 7;`
     */
    public var log: mrt.Mrt.GitLogReq
      @kotlin.jvm.JvmName("getLog")
        get() = _builder.log
      @kotlin.jvm.JvmName("setLog")
        set(value) {
        _builder.log = value
      }
    /**
     * `.mrt.GitLogReq log = 7;`
     */
    public fun clearLog() {
      _builder.clearLog()
    }
    /**
     * `.mrt.GitLogReq log = 7;`
     * @return Whether the log field is set.
     */
    public fun hasLog(): kotlin.Boolean {
      return _builder.hasLog()
    }

    /**
     * `.mrt.GitBranchesReq branches = 8;`
     */
    public var branches: mrt.Mrt.GitBranchesReq
      @kotlin.jvm.JvmName("getBranches")
        get() = _builder.branches
      @kotlin.jvm.JvmName("setBranches")
        set(value) {
        _builder.branches = value
      }
    /**
     * `.mrt.GitBranchesReq branches = 8;`
     */
    public fun clearBranches() {
      _builder.clearBranches()
    }
    /**
     * `.mrt.GitBranchesReq branches = 8;`
     * @return Whether the branches field is set.
     */
    public fun hasBranches(): kotlin.Boolean {
      return _builder.hasBranches()
    }

    /**
     * `.mrt.GitCheckoutReq checkout = 9;`
     */
    public var checkout: mrt.Mrt.GitCheckoutReq
      @kotlin.jvm.JvmName("getCheckout")
        get() = _builder.checkout
      @kotlin.jvm.JvmName("setCheckout")
        set(value) {
        _builder.checkout = value
      }
    /**
     * `.mrt.GitCheckoutReq checkout = 9;`
     */
    public fun clearCheckout() {
      _builder.clearCheckout()
    }
    /**
     * `.mrt.GitCheckoutReq checkout = 9;`
     * @return Whether the checkout field is set.
     */
    public fun hasCheckout(): kotlin.Boolean {
      return _builder.hasCheckout()
    }
    public val opCase: mrt.Mrt.GitOperation.OpCase
    @kotlin.jvm.JvmName("getOpCase")
      get() = _builder.getOpCase()

    public fun clearOp() {
      _builder.clearOp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitOperation.copy(block: `mrt`.GitOperationKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitOperation =
  `mrt`.GitOperationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.GitOperationOrBuilder.statusOrNull: mrt.Mrt.GitStatusReq?
  get() = if (hasStatus()) getStatus() else null

public val mrt.Mrt.GitOperationOrBuilder.commitOrNull: mrt.Mrt.GitCommitReq?
  get() = if (hasCommit()) getCommit() else null

public val mrt.Mrt.GitOperationOrBuilder.pushOrNull: mrt.Mrt.GitPushReq?
  get() = if (hasPush()) getPush() else null

public val mrt.Mrt.GitOperationOrBuilder.pullOrNull: mrt.Mrt.GitPullReq?
  get() = if (hasPull()) getPull() else null

public val mrt.Mrt.GitOperationOrBuilder.diffOrNull: mrt.Mrt.GitDiffReq?
  get() = if (hasDiff()) getDiff() else null

public val mrt.Mrt.GitOperationOrBuilder.logOrNull: mrt.Mrt.GitLogReq?
  get() = if (hasLog()) getLog() else null

public val mrt.Mrt.GitOperationOrBuilder.branchesOrNull: mrt.Mrt.GitBranchesReq?
  get() = if (hasBranches()) getBranches() else null

public val mrt.Mrt.GitOperationOrBuilder.checkoutOrNull: mrt.Mrt.GitCheckoutReq?
  get() = if (hasCheckout()) getCheckout() else null

