// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitPullReq")
public inline fun gitPullReq(block: mrt.GitPullReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitPullReq =
  mrt.GitPullReqKt.Dsl._create(mrt.Mrt.GitPullReq.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitPullReq`
 */
public object GitPullReqKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitPullReq.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitPullReq.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitPullReq = _builder.build()

    /**
     * `string remote = 1;`
     */
    public var remote: kotlin.String
      @kotlin.jvm.JvmName("getRemote")
        get() = _builder.remote
      @kotlin.jvm.JvmName("setRemote")
        set(value) {
        _builder.remote = value
      }
    /**
     * `string remote = 1;`
     */
    public fun clearRemote() {
      _builder.clearRemote()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitPullReq.copy(block: `mrt`.GitPullReqKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitPullReq =
  `mrt`.GitPullReqKt.Dsl._create(this.toBuilder()).apply { block() }._build()

