// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitResult")
public inline fun gitResult(block: mrt.GitResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitResult =
  mrt.GitResultKt.Dsl._create(mrt.Mrt.GitResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitResult`
 */
public object GitResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitResult = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `.mrt.GitStatusResult status = 2;`
     */
    public var status: mrt.Mrt.GitStatusResult
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * `.mrt.GitStatusResult status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * `.mrt.GitStatusResult status = 2;`
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * `.mrt.GitDiffResult diff = 3;`
     */
    public var diff: mrt.Mrt.GitDiffResult
      @kotlin.jvm.JvmName("getDiff")
        get() = _builder.diff
      @kotlin.jvm.JvmName("setDiff")
        set(value) {
        _builder.diff = value
      }
    /**
     * `.mrt.GitDiffResult diff = 3;`
     */
    public fun clearDiff() {
      _builder.clearDiff()
    }
    /**
     * `.mrt.GitDiffResult diff = 3;`
     * @return Whether the diff field is set.
     */
    public fun hasDiff(): kotlin.Boolean {
      return _builder.hasDiff()
    }

    /**
     * `.mrt.GitLogResult log = 4;`
     */
    public var log: mrt.Mrt.GitLogResult
      @kotlin.jvm.JvmName("getLog")
        get() = _builder.log
      @kotlin.jvm.JvmName("setLog")
        set(value) {
        _builder.log = value
      }
    /**
     * `.mrt.GitLogResult log = 4;`
     */
    public fun clearLog() {
      _builder.clearLog()
    }
    /**
     * `.mrt.GitLogResult log = 4;`
     * @return Whether the log field is set.
     */
    public fun hasLog(): kotlin.Boolean {
      return _builder.hasLog()
    }

    /**
     * `.mrt.GitBranchesResult branches = 5;`
     */
    public var branches: mrt.Mrt.GitBranchesResult
      @kotlin.jvm.JvmName("getBranches")
        get() = _builder.branches
      @kotlin.jvm.JvmName("setBranches")
        set(value) {
        _builder.branches = value
      }
    /**
     * `.mrt.GitBranchesResult branches = 5;`
     */
    public fun clearBranches() {
      _builder.clearBranches()
    }
    /**
     * `.mrt.GitBranchesResult branches = 5;`
     * @return Whether the branches field is set.
     */
    public fun hasBranches(): kotlin.Boolean {
      return _builder.hasBranches()
    }

    /**
     * `.mrt.GitOperationAck ack = 6;`
     */
    public var ack: mrt.Mrt.GitOperationAck
      @kotlin.jvm.JvmName("getAck")
        get() = _builder.ack
      @kotlin.jvm.JvmName("setAck")
        set(value) {
        _builder.ack = value
      }
    /**
     * `.mrt.GitOperationAck ack = 6;`
     */
    public fun clearAck() {
      _builder.clearAck()
    }
    /**
     * `.mrt.GitOperationAck ack = 6;`
     * @return Whether the ack field is set.
     */
    public fun hasAck(): kotlin.Boolean {
      return _builder.hasAck()
    }

    /**
     * `.mrt.ErrorEvent error = 10;`
     */
    public var error: mrt.Mrt.ErrorEvent
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `.mrt.ErrorEvent error = 10;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `.mrt.ErrorEvent error = 10;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }
    public val resultCase: mrt.Mrt.GitResult.ResultCase
    @kotlin.jvm.JvmName("getResultCase")
      get() = _builder.getResultCase()

    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitResult.copy(block: `mrt`.GitResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitResult =
  `mrt`.GitResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.GitResultOrBuilder.statusOrNull: mrt.Mrt.GitStatusResult?
  get() = if (hasStatus()) getStatus() else null

public val mrt.Mrt.GitResultOrBuilder.diffOrNull: mrt.Mrt.GitDiffResult?
  get() = if (hasDiff()) getDiff() else null

public val mrt.Mrt.GitResultOrBuilder.logOrNull: mrt.Mrt.GitLogResult?
  get() = if (hasLog()) getLog() else null

public val mrt.Mrt.GitResultOrBuilder.branchesOrNull: mrt.Mrt.GitBranchesResult?
  get() = if (hasBranches()) getBranches() else null

public val mrt.Mrt.GitResultOrBuilder.ackOrNull: mrt.Mrt.GitOperationAck?
  get() = if (hasAck()) getAck() else null

public val mrt.Mrt.GitResultOrBuilder.errorOrNull: mrt.Mrt.ErrorEvent?
  get() = if (hasError()) getError() else null

