// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializegitStatusResult")
public inline fun gitStatusResult(block: mrt.GitStatusResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitStatusResult =
  mrt.GitStatusResultKt.Dsl._create(mrt.Mrt.GitStatusResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.GitStatusResult`
 */
public object GitStatusResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.GitStatusResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.GitStatusResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.GitStatusResult = _builder.build()

    /**
     * `string branch = 1;`
     */
    public var branch: kotlin.String
      @kotlin.jvm.JvmName("getBranch")
        get() = _builder.branch
      @kotlin.jvm.JvmName("setBranch")
        set(value) {
        _builder.branch = value
      }
    /**
     * `string branch = 1;`
     */
    public fun clearBranch() {
      _builder.clearBranch()
    }

    /**
     * `string tracking = 2;`
     */
    public var tracking: kotlin.String
      @kotlin.jvm.JvmName("getTracking")
        get() = _builder.tracking
      @kotlin.jvm.JvmName("setTracking")
        set(value) {
        _builder.tracking = value
      }
    /**
     * `string tracking = 2;`
     */
    public fun clearTracking() {
      _builder.clearTracking()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChangesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .mrt.GitFileChange changes = 3;`
     */
     public val changes: com.google.protobuf.kotlin.DslList<mrt.Mrt.GitFileChange, ChangesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.changesList
      )
    /**
     * `repeated .mrt.GitFileChange changes = 3;`
     * @param value The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addChanges")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitFileChange, ChangesProxy>.add(value: mrt.Mrt.GitFileChange) {
      _builder.addChanges(value)
    }
    /**
     * `repeated .mrt.GitFileChange changes = 3;`
     * @param value The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignChanges")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitFileChange, ChangesProxy>.plusAssign(value: mrt.Mrt.GitFileChange) {
      add(value)
    }
    /**
     * `repeated .mrt.GitFileChange changes = 3;`
     * @param values The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllChanges")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitFileChange, ChangesProxy>.addAll(values: kotlin.collections.Iterable<mrt.Mrt.GitFileChange>) {
      _builder.addAllChanges(values)
    }
    /**
     * `repeated .mrt.GitFileChange changes = 3;`
     * @param values The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllChanges")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitFileChange, ChangesProxy>.plusAssign(values: kotlin.collections.Iterable<mrt.Mrt.GitFileChange>) {
      addAll(values)
    }
    /**
     * `repeated .mrt.GitFileChange changes = 3;`
     * @param index The index to set the value at.
     * @param value The changes to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setChanges")
    public operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitFileChange, ChangesProxy>.set(index: kotlin.Int, value: mrt.Mrt.GitFileChange) {
      _builder.setChanges(index, value)
    }
    /**
     * `repeated .mrt.GitFileChange changes = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearChanges")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.GitFileChange, ChangesProxy>.clear() {
      _builder.clearChanges()
    }

    /**
     * `bool is_clean = 4;`
     */
    public var isClean: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsClean")
        get() = _builder.isClean
      @kotlin.jvm.JvmName("setIsClean")
        set(value) {
        _builder.isClean = value
      }
    /**
     * `bool is_clean = 4;`
     */
    public fun clearIsClean() {
      _builder.clearIsClean()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.GitStatusResult.copy(block: `mrt`.GitStatusResultKt.Dsl.() -> kotlin.Unit): mrt.Mrt.GitStatusResult =
  `mrt`.GitStatusResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

