// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializehandshake")
public inline fun handshake(block: mrt.HandshakeKt.Dsl.() -> kotlin.Unit): mrt.Mrt.Handshake =
  mrt.HandshakeKt.Dsl._create(mrt.Mrt.Handshake.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.Handshake`
 */
public object HandshakeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.Handshake.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.Handshake.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.Handshake = _builder.build()

    /**
     * `uint32 protocol_version = 1;`
     */
    public var protocolVersion: kotlin.Int
      @kotlin.jvm.JvmName("getProtocolVersion")
        get() = _builder.protocolVersion
      @kotlin.jvm.JvmName("setProtocolVersion")
        set(value) {
        _builder.protocolVersion = value
      }
    /**
     * `uint32 protocol_version = 1;`
     */
    public fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }

    /**
     * `.mrt.ClientType client_type = 2;`
     */
    public var clientType: mrt.Mrt.ClientType
      @kotlin.jvm.JvmName("getClientType")
        get() = _builder.clientType
      @kotlin.jvm.JvmName("setClientType")
        set(value) {
        _builder.clientType = value
      }
    public var clientTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getClientTypeValue")
        get() = _builder.clientTypeValue
      @kotlin.jvm.JvmName("setClientTypeValue")
        set(value) {
        _builder.clientTypeValue = value
      }
    /**
     * `.mrt.ClientType client_type = 2;`
     */
    public fun clearClientType() {
      _builder.clearClientType()
    }

    /**
     * ```
     * semver, e.g. "1.0.0"
     * ```
     *
     * `string client_version = 3;`
     */
    public var clientVersion: kotlin.String
      @kotlin.jvm.JvmName("getClientVersion")
        get() = _builder.clientVersion
      @kotlin.jvm.JvmName("setClientVersion")
        set(value) {
        _builder.clientVersion = value
      }
    /**
     * ```
     * semver, e.g. "1.0.0"
     * ```
     *
     * `string client_version = 3;`
     */
    public fun clearClientVersion() {
      _builder.clearClientVersion()
    }

    /**
     * `string device_id = 4;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 4;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.Handshake.copy(block: `mrt`.HandshakeKt.Dsl.() -> kotlin.Unit): mrt.Mrt.Handshake =
  `mrt`.HandshakeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

