// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeheartbeat")
public inline fun heartbeat(block: mrt.HeartbeatKt.Dsl.() -> kotlin.Unit): mrt.Mrt.Heartbeat =
  mrt.HeartbeatKt.Dsl._create(mrt.Mrt.Heartbeat.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.Heartbeat`
 */
public object HeartbeatKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.Heartbeat.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.Heartbeat.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.Heartbeat = _builder.build()

    /**
     * `uint64 timestamp_ms = 1;`
     */
    public var timestampMs: kotlin.Long
      @kotlin.jvm.JvmName("getTimestampMs")
        get() = _builder.timestampMs
      @kotlin.jvm.JvmName("setTimestampMs")
        set(value) {
        _builder.timestampMs = value
      }
    /**
     * `uint64 timestamp_ms = 1;`
     */
    public fun clearTimestampMs() {
      _builder.clearTimestampMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.Heartbeat.copy(block: `mrt`.HeartbeatKt.Dsl.() -> kotlin.Unit): mrt.Mrt.Heartbeat =
  `mrt`.HeartbeatKt.Dsl._create(this.toBuilder()).apply { block() }._build()

