// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeiceCandidate")
public inline fun iceCandidate(block: mrt.IceCandidateKt.Dsl.() -> kotlin.Unit): mrt.Mrt.IceCandidate =
  mrt.IceCandidateKt.Dsl._create(mrt.Mrt.IceCandidate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.IceCandidate`
 */
public object IceCandidateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.IceCandidate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.IceCandidate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.IceCandidate = _builder.build()

    /**
     * `string target_device_id = 1;`
     */
    public var targetDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getTargetDeviceId")
        get() = _builder.targetDeviceId
      @kotlin.jvm.JvmName("setTargetDeviceId")
        set(value) {
        _builder.targetDeviceId = value
      }
    /**
     * `string target_device_id = 1;`
     */
    public fun clearTargetDeviceId() {
      _builder.clearTargetDeviceId()
    }

    /**
     * ```
     * SDP candidate string
     * ```
     *
     * `string candidate = 2;`
     */
    public var candidate: kotlin.String
      @kotlin.jvm.JvmName("getCandidate")
        get() = _builder.candidate
      @kotlin.jvm.JvmName("setCandidate")
        set(value) {
        _builder.candidate = value
      }
    /**
     * ```
     * SDP candidate string
     * ```
     *
     * `string candidate = 2;`
     */
    public fun clearCandidate() {
      _builder.clearCandidate()
    }

    /**
     * `string sdp_mid = 3;`
     */
    public var sdpMid: kotlin.String
      @kotlin.jvm.JvmName("getSdpMid")
        get() = _builder.sdpMid
      @kotlin.jvm.JvmName("setSdpMid")
        set(value) {
        _builder.sdpMid = value
      }
    /**
     * `string sdp_mid = 3;`
     */
    public fun clearSdpMid() {
      _builder.clearSdpMid()
    }

    /**
     * `uint32 sdp_mline_index = 4;`
     */
    public var sdpMlineIndex: kotlin.Int
      @kotlin.jvm.JvmName("getSdpMlineIndex")
        get() = _builder.sdpMlineIndex
      @kotlin.jvm.JvmName("setSdpMlineIndex")
        set(value) {
        _builder.sdpMlineIndex = value
      }
    /**
     * `uint32 sdp_mline_index = 4;`
     */
    public fun clearSdpMlineIndex() {
      _builder.clearSdpMlineIndex()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.IceCandidate.copy(block: `mrt`.IceCandidateKt.Dsl.() -> kotlin.Unit): mrt.Mrt.IceCandidate =
  `mrt`.IceCandidateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

