// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializeiceOffer")
public inline fun iceOffer(block: mrt.IceOfferKt.Dsl.() -> kotlin.Unit): mrt.Mrt.IceOffer =
  mrt.IceOfferKt.Dsl._create(mrt.Mrt.IceOffer.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.IceOffer`
 */
public object IceOfferKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.IceOffer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.IceOffer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.IceOffer = _builder.build()

    /**
     * `string target_device_id = 1;`
     */
    public var targetDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getTargetDeviceId")
        get() = _builder.targetDeviceId
      @kotlin.jvm.JvmName("setTargetDeviceId")
        set(value) {
        _builder.targetDeviceId = value
      }
    /**
     * `string target_device_id = 1;`
     */
    public fun clearTargetDeviceId() {
      _builder.clearTargetDeviceId()
    }

    /**
     * `string sdp = 2;`
     */
    public var sdp: kotlin.String
      @kotlin.jvm.JvmName("getSdp")
        get() = _builder.sdp
      @kotlin.jvm.JvmName("setSdp")
        set(value) {
        _builder.sdp = value
      }
    /**
     * `string sdp = 2;`
     */
    public fun clearSdp() {
      _builder.clearSdp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.IceOffer.copy(block: `mrt`.IceOfferKt.Dsl.() -> kotlin.Unit): mrt.Mrt.IceOffer =
  `mrt`.IceOfferKt.Dsl._create(this.toBuilder()).apply { block() }._build()

