// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializelistSessions")
public inline fun listSessions(block: mrt.ListSessionsKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ListSessions =
  mrt.ListSessionsKt.Dsl._create(mrt.Mrt.ListSessions.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ListSessions`
 */
public object ListSessionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ListSessions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ListSessions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ListSessions = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ListSessions.copy(block: `mrt`.ListSessionsKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ListSessions =
  `mrt`.ListSessionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

