// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializelistDir")
public inline fun listDir(block: mrt.ListDirKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ListDir =
  mrt.ListDirKt.Dsl._create(mrt.Mrt.ListDir.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ListDir`
 */
public object ListDirKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ListDir.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ListDir.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ListDir = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `bool recursive = 2;`
     */
    public var recursive: kotlin.Boolean
      @kotlin.jvm.JvmName("getRecursive")
        get() = _builder.recursive
      @kotlin.jvm.JvmName("setRecursive")
        set(value) {
        _builder.recursive = value
      }
    /**
     * `bool recursive = 2;`
     */
    public fun clearRecursive() {
      _builder.clearRecursive()
    }

    /**
     * `uint32 max_depth = 3;`
     */
    public var maxDepth: kotlin.Int
      @kotlin.jvm.JvmName("getMaxDepth")
        get() = _builder.maxDepth
      @kotlin.jvm.JvmName("setMaxDepth")
        set(value) {
        _builder.maxDepth = value
      }
    /**
     * `uint32 max_depth = 3;`
     */
    public fun clearMaxDepth() {
      _builder.clearMaxDepth()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ListDir.copy(block: `mrt`.ListDirKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ListDir =
  `mrt`.ListDirKt.Dsl._create(this.toBuilder()).apply { block() }._build()

