// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializereadFile")
public inline fun readFile(block: mrt.ReadFileKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ReadFile =
  mrt.ReadFileKt.Dsl._create(mrt.Mrt.ReadFile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.ReadFile`
 */
public object ReadFileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.ReadFile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.ReadFile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.ReadFile = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `uint64 offset = 2;`
     */
    public var offset: kotlin.Long
      @kotlin.jvm.JvmName("getOffset")
        get() = _builder.offset
      @kotlin.jvm.JvmName("setOffset")
        set(value) {
        _builder.offset = value
      }
    /**
     * `uint64 offset = 2;`
     */
    public fun clearOffset() {
      _builder.clearOffset()
    }

    /**
     * `uint64 length = 3;`
     */
    public var length: kotlin.Long
      @kotlin.jvm.JvmName("getLength")
        get() = _builder.length
      @kotlin.jvm.JvmName("setLength")
        set(value) {
        _builder.length = value
      }
    /**
     * `uint64 length = 3;`
     */
    public fun clearLength() {
      _builder.clearLength()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.ReadFile.copy(block: `mrt`.ReadFileKt.Dsl.() -> kotlin.Unit): mrt.Mrt.ReadFile =
  `mrt`.ReadFileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

