// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializerenameSession")
public inline fun renameSession(block: mrt.RenameSessionKt.Dsl.() -> kotlin.Unit): mrt.Mrt.RenameSession =
  mrt.RenameSessionKt.Dsl._create(mrt.Mrt.RenameSession.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.RenameSession`
 */
public object RenameSessionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.RenameSession.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.RenameSession.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.RenameSession = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string new_name = 2;`
     */
    public var newName: kotlin.String
      @kotlin.jvm.JvmName("getNewName")
        get() = _builder.newName
      @kotlin.jvm.JvmName("setNewName")
        set(value) {
        _builder.newName = value
      }
    /**
     * `string new_name = 2;`
     */
    public fun clearNewName() {
      _builder.clearNewName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.RenameSession.copy(block: `mrt`.RenameSessionKt.Dsl.() -> kotlin.Unit): mrt.Mrt.RenameSession =
  `mrt`.RenameSessionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

