// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializerenamePath")
public inline fun renamePath(block: mrt.RenamePathKt.Dsl.() -> kotlin.Unit): mrt.Mrt.RenamePath =
  mrt.RenamePathKt.Dsl._create(mrt.Mrt.RenamePath.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.RenamePath`
 */
public object RenamePathKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.RenamePath.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.RenamePath.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.RenamePath = _builder.build()

    /**
     * `string from_path = 1;`
     */
    public var fromPath: kotlin.String
      @kotlin.jvm.JvmName("getFromPath")
        get() = _builder.fromPath
      @kotlin.jvm.JvmName("setFromPath")
        set(value) {
        _builder.fromPath = value
      }
    /**
     * `string from_path = 1;`
     */
    public fun clearFromPath() {
      _builder.clearFromPath()
    }

    /**
     * `string to_path = 2;`
     */
    public var toPath: kotlin.String
      @kotlin.jvm.JvmName("getToPath")
        get() = _builder.toPath
      @kotlin.jvm.JvmName("setToPath")
        set(value) {
        _builder.toPath = value
      }
    /**
     * `string to_path = 2;`
     */
    public fun clearToPath() {
      _builder.clearToPath()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.RenamePath.copy(block: `mrt`.RenamePathKt.Dsl.() -> kotlin.Unit): mrt.Mrt.RenamePath =
  `mrt`.RenamePathKt.Dsl._create(this.toBuilder()).apply { block() }._build()

