// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializesendPrompt")
public inline fun sendPrompt(block: mrt.SendPromptKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SendPrompt =
  mrt.SendPromptKt.Dsl._create(mrt.Mrt.SendPrompt.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.SendPrompt`
 */
public object SendPromptKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.SendPrompt.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.SendPrompt.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.SendPrompt = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string prompt = 2;`
     */
    public var prompt: kotlin.String
      @kotlin.jvm.JvmName("getPrompt")
        get() = _builder.prompt
      @kotlin.jvm.JvmName("setPrompt")
        set(value) {
        _builder.prompt = value
      }
    /**
     * `string prompt = 2;`
     */
    public fun clearPrompt() {
      _builder.clearPrompt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.SendPrompt.copy(block: `mrt`.SendPromptKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SendPrompt =
  `mrt`.SendPromptKt.Dsl._create(this.toBuilder()).apply { block() }._build()

