// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializesessionInfo")
public inline fun sessionInfo(block: mrt.SessionInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SessionInfo =
  mrt.SessionInfoKt.Dsl._create(mrt.Mrt.SessionInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.SessionInfo`
 */
public object SessionInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.SessionInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.SessionInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.SessionInfo = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.mrt.TaskStatus status = 3;`
     */
    public var status: mrt.Mrt.TaskStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.mrt.TaskStatus status = 3;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `uint64 created_at_ms = 4;`
     */
    public var createdAtMs: kotlin.Long
      @kotlin.jvm.JvmName("getCreatedAtMs")
        get() = _builder.createdAtMs
      @kotlin.jvm.JvmName("setCreatedAtMs")
        set(value) {
        _builder.createdAtMs = value
      }
    /**
     * `uint64 created_at_ms = 4;`
     */
    public fun clearCreatedAtMs() {
      _builder.clearCreatedAtMs()
    }

    /**
     * `uint64 last_active_ms = 5;`
     */
    public var lastActiveMs: kotlin.Long
      @kotlin.jvm.JvmName("getLastActiveMs")
        get() = _builder.lastActiveMs
      @kotlin.jvm.JvmName("setLastActiveMs")
        set(value) {
        _builder.lastActiveMs = value
      }
    /**
     * `uint64 last_active_ms = 5;`
     */
    public fun clearLastActiveMs() {
      _builder.clearLastActiveMs()
    }

    /**
     * ```
     * project directory for this session
     * ```
     *
     * `string working_dir = 6;`
     */
    public var workingDir: kotlin.String
      @kotlin.jvm.JvmName("getWorkingDir")
        get() = _builder.workingDir
      @kotlin.jvm.JvmName("setWorkingDir")
        set(value) {
        _builder.workingDir = value
      }
    /**
     * ```
     * project directory for this session
     * ```
     *
     * `string working_dir = 6;`
     */
    public fun clearWorkingDir() {
      _builder.clearWorkingDir()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.SessionInfo.copy(block: `mrt`.SessionInfoKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SessionInfo =
  `mrt`.SessionInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

