// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializesessionControl")
public inline fun sessionControl(block: mrt.SessionControlKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SessionControl =
  mrt.SessionControlKt.Dsl._create(mrt.Mrt.SessionControl.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.SessionControl`
 */
public object SessionControlKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.SessionControl.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.SessionControl.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.SessionControl = _builder.build()

    /**
     * `.mrt.CreateSession create = 1;`
     */
    public var create: mrt.Mrt.CreateSession
      @kotlin.jvm.JvmName("getCreate")
        get() = _builder.create
      @kotlin.jvm.JvmName("setCreate")
        set(value) {
        _builder.create = value
      }
    /**
     * `.mrt.CreateSession create = 1;`
     */
    public fun clearCreate() {
      _builder.clearCreate()
    }
    /**
     * `.mrt.CreateSession create = 1;`
     * @return Whether the create field is set.
     */
    public fun hasCreate(): kotlin.Boolean {
      return _builder.hasCreate()
    }

    /**
     * `.mrt.SwitchSession switch_to = 2;`
     */
    public var switchTo: mrt.Mrt.SwitchSession
      @kotlin.jvm.JvmName("getSwitchTo")
        get() = _builder.switchTo
      @kotlin.jvm.JvmName("setSwitchTo")
        set(value) {
        _builder.switchTo = value
      }
    /**
     * `.mrt.SwitchSession switch_to = 2;`
     */
    public fun clearSwitchTo() {
      _builder.clearSwitchTo()
    }
    /**
     * `.mrt.SwitchSession switch_to = 2;`
     * @return Whether the switchTo field is set.
     */
    public fun hasSwitchTo(): kotlin.Boolean {
      return _builder.hasSwitchTo()
    }

    /**
     * `.mrt.CloseSession close = 3;`
     */
    public var close: mrt.Mrt.CloseSession
      @kotlin.jvm.JvmName("getClose")
        get() = _builder.close
      @kotlin.jvm.JvmName("setClose")
        set(value) {
        _builder.close = value
      }
    /**
     * `.mrt.CloseSession close = 3;`
     */
    public fun clearClose() {
      _builder.clearClose()
    }
    /**
     * `.mrt.CloseSession close = 3;`
     * @return Whether the close field is set.
     */
    public fun hasClose(): kotlin.Boolean {
      return _builder.hasClose()
    }

    /**
     * `.mrt.ListSessions list = 4;`
     */
    public var list: mrt.Mrt.ListSessions
      @kotlin.jvm.JvmName("getList")
        get() = _builder.list
      @kotlin.jvm.JvmName("setList")
        set(value) {
        _builder.list = value
      }
    /**
     * `.mrt.ListSessions list = 4;`
     */
    public fun clearList() {
      _builder.clearList()
    }
    /**
     * `.mrt.ListSessions list = 4;`
     * @return Whether the list field is set.
     */
    public fun hasList(): kotlin.Boolean {
      return _builder.hasList()
    }

    /**
     * `.mrt.RenameSession rename = 5;`
     */
    public var rename: mrt.Mrt.RenameSession
      @kotlin.jvm.JvmName("getRename")
        get() = _builder.rename
      @kotlin.jvm.JvmName("setRename")
        set(value) {
        _builder.rename = value
      }
    /**
     * `.mrt.RenameSession rename = 5;`
     */
    public fun clearRename() {
      _builder.clearRename()
    }
    /**
     * `.mrt.RenameSession rename = 5;`
     * @return Whether the rename field is set.
     */
    public fun hasRename(): kotlin.Boolean {
      return _builder.hasRename()
    }
    public val actionCase: mrt.Mrt.SessionControl.ActionCase
    @kotlin.jvm.JvmName("getActionCase")
      get() = _builder.getActionCase()

    public fun clearAction() {
      _builder.clearAction()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.SessionControl.copy(block: `mrt`.SessionControlKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SessionControl =
  `mrt`.SessionControlKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val mrt.Mrt.SessionControlOrBuilder.createOrNull: mrt.Mrt.CreateSession?
  get() = if (hasCreate()) getCreate() else null

public val mrt.Mrt.SessionControlOrBuilder.switchToOrNull: mrt.Mrt.SwitchSession?
  get() = if (hasSwitchTo()) getSwitchTo() else null

public val mrt.Mrt.SessionControlOrBuilder.closeOrNull: mrt.Mrt.CloseSession?
  get() = if (hasClose()) getClose() else null

public val mrt.Mrt.SessionControlOrBuilder.listOrNull: mrt.Mrt.ListSessions?
  get() = if (hasList()) getList() else null

public val mrt.Mrt.SessionControlOrBuilder.renameOrNull: mrt.Mrt.RenameSession?
  get() = if (hasRename()) getRename() else null

