// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializesessionListUpdate")
public inline fun sessionListUpdate(block: mrt.SessionListUpdateKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SessionListUpdate =
  mrt.SessionListUpdateKt.Dsl._create(mrt.Mrt.SessionListUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.SessionListUpdate`
 */
public object SessionListUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.SessionListUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.SessionListUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.SessionListUpdate = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SessionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .mrt.SessionInfo sessions = 1;`
     */
     public val sessions: com.google.protobuf.kotlin.DslList<mrt.Mrt.SessionInfo, SessionsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.sessionsList
      )
    /**
     * `repeated .mrt.SessionInfo sessions = 1;`
     * @param value The sessions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSessions")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.SessionInfo, SessionsProxy>.add(value: mrt.Mrt.SessionInfo) {
      _builder.addSessions(value)
    }
    /**
     * `repeated .mrt.SessionInfo sessions = 1;`
     * @param value The sessions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSessions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.SessionInfo, SessionsProxy>.plusAssign(value: mrt.Mrt.SessionInfo) {
      add(value)
    }
    /**
     * `repeated .mrt.SessionInfo sessions = 1;`
     * @param values The sessions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSessions")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.SessionInfo, SessionsProxy>.addAll(values: kotlin.collections.Iterable<mrt.Mrt.SessionInfo>) {
      _builder.addAllSessions(values)
    }
    /**
     * `repeated .mrt.SessionInfo sessions = 1;`
     * @param values The sessions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSessions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.SessionInfo, SessionsProxy>.plusAssign(values: kotlin.collections.Iterable<mrt.Mrt.SessionInfo>) {
      addAll(values)
    }
    /**
     * `repeated .mrt.SessionInfo sessions = 1;`
     * @param index The index to set the value at.
     * @param value The sessions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSessions")
    public operator fun com.google.protobuf.kotlin.DslList<mrt.Mrt.SessionInfo, SessionsProxy>.set(index: kotlin.Int, value: mrt.Mrt.SessionInfo) {
      _builder.setSessions(index, value)
    }
    /**
     * `repeated .mrt.SessionInfo sessions = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSessions")
    public fun com.google.protobuf.kotlin.DslList<mrt.Mrt.SessionInfo, SessionsProxy>.clear() {
      _builder.clearSessions()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.SessionListUpdate.copy(block: `mrt`.SessionListUpdateKt.Dsl.() -> kotlin.Unit): mrt.Mrt.SessionListUpdate =
  `mrt`.SessionListUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

