// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializetaskStatusUpdate")
public inline fun taskStatusUpdate(block: mrt.TaskStatusUpdateKt.Dsl.() -> kotlin.Unit): mrt.Mrt.TaskStatusUpdate =
  mrt.TaskStatusUpdateKt.Dsl._create(mrt.Mrt.TaskStatusUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.TaskStatusUpdate`
 */
public object TaskStatusUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.TaskStatusUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.TaskStatusUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.TaskStatusUpdate = _builder.build()

    /**
     * `string session_id = 1;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `.mrt.TaskStatus status = 2;`
     */
    public var status: mrt.Mrt.TaskStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.mrt.TaskStatus status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * short description of what happened
     * ```
     *
     * `string summary = 3;`
     */
    public var summary: kotlin.String
      @kotlin.jvm.JvmName("getSummary")
        get() = _builder.summary
      @kotlin.jvm.JvmName("setSummary")
        set(value) {
        _builder.summary = value
      }
    /**
     * ```
     * short description of what happened
     * ```
     *
     * `string summary = 3;`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.TaskStatusUpdate.copy(block: `mrt`.TaskStatusUpdateKt.Dsl.() -> kotlin.Unit): mrt.Mrt.TaskStatusUpdate =
  `mrt`.TaskStatusUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

