// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mrt.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package mrt;

@kotlin.jvm.JvmName("-initializewriteFile")
public inline fun writeFile(block: mrt.WriteFileKt.Dsl.() -> kotlin.Unit): mrt.Mrt.WriteFile =
  mrt.WriteFileKt.Dsl._create(mrt.Mrt.WriteFile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mrt.WriteFile`
 */
public object WriteFileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: mrt.Mrt.WriteFile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: mrt.Mrt.WriteFile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): mrt.Mrt.WriteFile = _builder.build()

    /**
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `bytes content = 2;`
     */
    public var content: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `bytes content = 2;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun mrt.Mrt.WriteFile.copy(block: `mrt`.WriteFileKt.Dsl.() -> kotlin.Unit): mrt.Mrt.WriteFile =
  `mrt`.WriteFileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

